project:
  type: website

website:
  title: "Robert's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rmporsch
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-milan-porsch-376705123/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


