<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robert Porsch">
<meta name="dcterms.date" content="2021-05-22">
<meta name="description" content="As part of my MBA with the University of Warwick, I studied collaboration among firms in open-source software projects. I found that single-firm dominance and license restrictiveness hinder collaboration, while diversity in collaboration has a U-shaped effect on productivity. My findings suggest that firms should provide opportunities for collaboration and balance hierarchical controls to attract partners and enhance productivity.">

<title>Robert’s Blog - Open Source, Open Collaboration: A Statistical Analysis of Firm Interactions in Software Development.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Robert’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rmporsch"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/robert-milan-porsch-376705123/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Open Source, Open Collaboration: A Statistical Analysis of Firm Interactions in Software Development.</h1>
                  <div>
        <div class="description">
          As part of my MBA with the University of Warwick, I studied collaboration among firms in open-source software projects. I found that single-firm dominance and license restrictiveness hinder collaboration, while diversity in collaboration has a U-shaped effect on productivity. My findings suggest that firms should provide opportunities for collaboration and balance hierarchical controls to attract partners and enhance productivity.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">thesis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Robert Porsch </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 22, 2021</p>
      </div>
    </div>
    
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="block-title">Abstract</div>
      <p>In the past decade, there has been a growing trend of firms participating in open-source software (OSS) development and collaboration. However, while previous research has focused on the strategic objectives and incentives that drive firms to engage in OSS, there has been a lack of investigation into the project-level factors that promote active collaboration among firms. Additionally, little research has been done to explore how the composition of corporate collaborators affects project productivity.</p>
      <p>To address this gap, this study draws on the Resource-based view (RBV) and Transaction cost economic theory (TCE) to develop several hypotheses that identify predictors of corporate collaboration in OSS projects. The study uses a sample of 1,127 OSS projects from the popular code collaboration platform GitHub and conducts a regression analysis to explore how license choice, code commit intensity, and network centrality affect corporate collaboration while controlling for confounding factors. Furthermore, Monte-Carlo analysis is used to test for non-linear relationships between collaboration heterogeneity and productivity.</p>
      <p>The results of this investigation reveal that single-firm dominance and license restrictiveness can hinder collaboration among firms, while the level of collaboration heterogeneity has a U-shaped effect on project productivity. These findings highlight the importance of firms providing opportunities for others to collaborate and balancing hierarchical controls within OSS projects when seeking to attract collaborating partners. Companies should also consider how collaboration diversity can impact productivity and develop practical and scalable governance mechanisms.</p>
      <p>Overall, this study contributes to our understanding of the factors that drive collaboration among firms in OSS projects and their impact on productivity. Future research could focus on scrutinizing the causal relationships between these factors.</p>
    </div>
  </div>
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#theory-and-hypotheses" id="toc-theory-and-hypotheses" class="nav-link" data-scroll-target="#theory-and-hypotheses">Theory and Hypotheses</a>
  <ul class="collapse">
  <li><a href="#hypothesis-1-control-through-domination" id="toc-hypothesis-1-control-through-domination" class="nav-link" data-scroll-target="#hypothesis-1-control-through-domination">Hypothesis 1: Control Through Domination</a></li>
  <li><a href="#hypothesis-2-control-through-licenses" id="toc-hypothesis-2-control-through-licenses" class="nav-link" data-scroll-target="#hypothesis-2-control-through-licenses">Hypothesis 2: Control through Licenses</a></li>
  <li><a href="#hypothesis-3-collaborations-heterogeneity-and-productivity" id="toc-hypothesis-3-collaborations-heterogeneity-and-productivity" class="nav-link" data-scroll-target="#hypothesis-3-collaborations-heterogeneity-and-productivity">Hypothesis 3: Collaborations heterogeneity and productivity</a></li>
  <li><a href="#hypothesis-4-collaboration-networks" id="toc-hypothesis-4-collaboration-networks" class="nav-link" data-scroll-target="#hypothesis-4-collaboration-networks">Hypothesis 4: Collaboration Networks</a></li>
  <li><a href="#hypothesis-5-interaction-between-contribution-intensity-and-network-value" id="toc-hypothesis-5-interaction-between-contribution-intensity-and-network-value" class="nav-link" data-scroll-target="#hypothesis-5-interaction-between-contribution-intensity-and-network-value">Hypothesis 5: Interaction between contribution intensity and network-value</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a>
  <ul class="collapse">
  <li><a href="#collecting-and-filtering" id="toc-collecting-and-filtering" class="nav-link" data-scroll-target="#collecting-and-filtering">Collecting and Filtering</a></li>
  <li><a href="#identification-of-developer-affiliation" id="toc-identification-of-developer-affiliation" class="nav-link" data-scroll-target="#identification-of-developer-affiliation">Identification of Developer Affiliation</a></li>
  </ul></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing">Data Processing</a>
  <ul class="collapse">
  <li><a href="#sssection:network-value" id="toc-sssection:network-value" class="nav-link" data-scroll-target="#sssection\:network-value">Firm’s Network Value</a></li>
  <li><a href="#project-characteristics" id="toc-project-characteristics" class="nav-link" data-scroll-target="#project-characteristics">Project Characteristics</a></li>
  <li><a href="#oss-project-license" id="toc-oss-project-license" class="nav-link" data-scroll-target="#oss-project-license">OSS Project License</a></li>
  <li><a href="#project-contribution-heterogeneity" id="toc-project-contribution-heterogeneity" class="nav-link" data-scroll-target="#project-contribution-heterogeneity">Project Contribution Heterogeneity</a></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a>
  <ul class="collapse">
  <li><a href="#statistical-modeling" id="toc-statistical-modeling" class="nav-link" data-scroll-target="#statistical-modeling">Statistical Modeling</a></li>
  <li><a href="#u-shape-analysis" id="toc-u-shape-analysis" class="nav-link" data-scroll-target="#u-shape-analysis">U-Shape Analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#descriptive-findings" id="toc-descriptive-findings" class="nav-link" data-scroll-target="#descriptive-findings">Descriptive Findings</a></li>
  <li><a href="#inferential-results" id="toc-inferential-results" class="nav-link" data-scroll-target="#inferential-results">Inferential Results</a>
  <ul class="collapse">
  <li><a href="#poisson-regression-results" id="toc-poisson-regression-results" class="nav-link" data-scroll-target="#poisson-regression-results">Poisson Regression Results</a></li>
  <li><a href="#u-shape-analysis-1" id="toc-u-shape-analysis-1" class="nav-link" data-scroll-target="#u-shape-analysis-1">U-Shape Analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#implications" id="toc-implications" class="nav-link" data-scroll-target="#implications">Implications</a>
  <ul class="collapse">
  <li><a href="#firm-commit-intensity" id="toc-firm-commit-intensity" class="nav-link" data-scroll-target="#firm-commit-intensity">Firm Commit Intensity</a></li>
  <li><a href="#sssec:licenses" id="toc-sssec:licenses" class="nav-link" data-scroll-target="#sssec\:licenses">Licenses</a></li>
  <li><a href="#sssec:network_centrality" id="toc-sssec:network_centrality" class="nav-link" data-scroll-target="#sssec\:network_centrality">Network Centrality</a></li>
  <li><a href="#productivity" id="toc-productivity" class="nav-link" data-scroll-target="#productivity">Productivity</a></li>
  </ul></li>
  <li><a href="#limitations-and-future-research" id="toc-limitations-and-future-research" class="nav-link" data-scroll-target="#limitations-and-future-research">Limitations and Future Research</a></li>
  <li><a href="#managerial-implications" id="toc-managerial-implications" class="nav-link" data-scroll-target="#managerial-implications">Managerial Implications</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Open-Source is an approach to how software is licensed and created, allowing anyone to inspect, modify, and improve the underlying source code <span class="citation" data-cites="perens1999">(<a href="#ref-perens1999" role="doc-biblioref">Perens 1999</a>)</span>. Open-Source Software (OSS) originated first within universities when software was freely distributed among scientists during the early 1950s <span class="citation" data-cites="dibona1999">(<a href="#ref-dibona1999" role="doc-biblioref">DiBona, Ockman, and Stone 1999</a>)</span>. This approach stands in contrast to proprietary software development, whose source code is only available to the organization which owns the underlying intellectual properties <span class="citation" data-cites="scott2003">(<a href="#ref-scott2003" role="doc-biblioref">Scott 2003</a>)</span>. OSS was first formalized by Richard Stallman in 1984 as Free Software under the GNU Project, aimed to provide a licensing framework for software created to be freely distributed <span class="citation" data-cites="perens1999">(<a href="#ref-perens1999" role="doc-biblioref">Perens 1999</a>)</span>. The Free Software Foundation later adopted this definition as the specification for what is now commonly referred to as open-source software <span class="citation" data-cites="debianfoundation2023">(<a href="#ref-debianfoundation2023" role="doc-biblioref">Debian Foundation 2023</a>)</span>.</p>
<p>The number of OSS projects has grown exponentially as the number of projects surged between 1990 and 2006 <span class="citation" data-cites="deshpande2008">(<a href="#ref-deshpande2008" role="doc-biblioref">Deshpande and Riehle 2008</a>)</span>. While OSS was mainly driven by independent developers donating their time and skills in the early years, commercial organizations are increasingly expanding their contributions. Specifically, developers paid by large information technology (IT) firms, such as Microsoft or Google, are often dominating OSS projects <span class="citation" data-cites="stephens2021">(<a href="#ref-stephens2021" role="doc-biblioref">Stephens 2021</a>)</span>. However, despite this significant growth over the last decade, there are some indications that this growth has been slowing in the last few years (<a href="#fig-repo_growth" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div id="fig-repo_growth" class="lightbox quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repo_growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/num_repos.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1"><img src="images/num_repos.png" class="img-fluid figure-img" style="width:55.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repo_growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Number of open-source repositories on the popular OSS collaboration platform GitHub between 2012 and 2022
</figcaption>
</figure>
</div>
<p>Nevertheless, increasingly corporations have adopted open source practices as a valuable addition to their strategic toolkit <span class="citation" data-cites="ahmad2021 bonaccorsi2007 germonprez2013 schaarschmidt2015 zhang2020a">(<a href="#ref-ahmad2021" role="doc-biblioref">Ahmad 2021</a>; <a href="#ref-bonaccorsi2007" role="doc-biblioref">Bonaccorsi et al. 2007</a>; <a href="#ref-germonprez2013" role="doc-biblioref">Germonprez et al. 2013</a>; <a href="#ref-schaarschmidt2015" role="doc-biblioref">Schaarschmidt, Walsh, and von Kortzfleisch 2015</a>; <a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>)</span>. <span class="citation" data-cites="blackduck2016">Black Duck (<a href="#ref-blackduck2016" role="doc-biblioref">2016</a>)</span> reported in their Open Source Survey that an estimated 65% of technology firms are actively contributing to OSS projects, demonstrating the increasing importance of OSS to firms. In financial terms, <span class="citation" data-cites="blind2023">Blind and Schubert (<a href="#ref-blind2023" role="doc-biblioref">2023</a>)</span> estimated the average impact of OSS at around 2.2% of today’s GDP per country, thus representing a sizable economic effect. This increase in corporate involvement is also seen in the composition of contributions to individual projects. For example, while traditionally, OSS projects were led by individual developers with no affiliation to specific firms, companies now contribute more than 90% to many well-known OSS projects such as the Linux Project <span class="citation" data-cites="zhang2020a">(<a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>)</span>.</p>
<p>While the growth and impact of OSS and the contributions of companies are well understood, the motivations behind these actions remain less clear <span class="citation" data-cites="germonprez2013 lerner2002 bonaccorsi2007">(<a href="#ref-germonprez2013" role="doc-biblioref">Germonprez et al. 2013</a>; <a href="#ref-lerner2002" role="doc-biblioref">Lerner and Tirole 2002</a>; <a href="#ref-bonaccorsi2007" role="doc-biblioref">Bonaccorsi et al. 2007</a>)</span>. Why would companies invest resources in research and development if the results of this labor would also be available to competitors? Previous research has aimed to answer this question by exploring the individual strategic objectives and incentives of firms to participate in OSS development <span class="citation" data-cites="germonprez2013 taherizadeh2019 ghapanchi2014 liu2022 nagle2019">(<a href="#ref-germonprez2013" role="doc-biblioref">Germonprez et al. 2013</a>; <a href="#ref-taherizadeh2019" role="doc-biblioref">Taherizadeh and Isabelle 2019</a>; <a href="#ref-ghapanchi2014" role="doc-biblioref">Ghapanchi, Wohlin, and Aurum 2014</a>; <a href="#ref-liu2022" role="doc-biblioref">Liu, Lai, and He 2022</a>; <a href="#ref-nagle2019" role="doc-biblioref">Nagle 2019</a>)</span>. However, little research has been done on the actual project-level factors predictive of corporate collaboration in OSS and how the degree of collaboration affects project productivity.</p>
</section>
<section id="theory-and-hypotheses" class="level1">
<h1>Theory and Hypotheses</h1>
<p>Collaborations in OSS are primarily understood through the lens of open innovation (OI) in the academic literature <span class="citation" data-cites="vanhaverbeke2014 chesbrough2014 west2006 gassmann2004 bogers2017">(<a href="#ref-vanhaverbeke2014" role="doc-biblioref">Vanhaverbeke and Cloodt 2014</a>; <a href="#ref-chesbrough2014" role="doc-biblioref">Chesbrough and Bogers 2014</a>; <a href="#ref-west2006" role="doc-biblioref">West and Gallagher 2006</a>; <a href="#ref-gassmann2004" role="doc-biblioref">Gassmann and Enkel 2004</a>; <a href="#ref-bogers2017" role="doc-biblioref">Bogers et al. 2017</a>)</span>. <span class="citation" data-cites="chesbrough2014">Chesbrough and Bogers (<a href="#ref-chesbrough2014" role="doc-biblioref">2014</a>)</span> referred to OI as a model that focuses on managed inflows and outflows of knowledge across the company boundary. As such, OI has focused on outside-in innovation, that is, the leverage of external knowledge to increase internal innovation, and inside-out innovation, which is the distribution of internal innovations to external parties. Thus, OI aims to manage the positive externalities that arise when knowledge generated through research and development (R&amp;D) activities by one firm spills over to other firms, also called spillover <span class="citation" data-cites="cheung2004">(<a href="#ref-cheung2004" role="doc-biblioref">Cheung and Lin 2004</a>)</span>. As this effect is unavoidable to prevent, OI utilizes specific mechanisms to direct this inflow and outflow of knowledge <span class="citation" data-cites="chesbrough2014">(<a href="#ref-chesbrough2014" role="doc-biblioref">Chesbrough and Bogers 2014</a>)</span>. In addition to these two processes, <span class="citation" data-cites="gassmann2004">Gassmann and Enkel (<a href="#ref-gassmann2004" role="doc-biblioref">2004</a>)</span> proposed a further innovation process called <em>coupled process</em>. This process can be seen as a combined outside-in, and inside-out mechanism in which two or more complementary firms collaborate (<a href="#fig-structural_approach" class="quarto-xref">Figure&nbsp;2</a>), also called <em>pooled R&amp;D</em> by <span class="citation" data-cites="west2006">West and Gallagher (<a href="#ref-west2006" role="doc-biblioref">2006</a>)</span>.</p>
<p>This <em>couple process</em> closely resembles OSS development practices in which a network of individual volunteers and organizations gather around a common goal <span class="citation" data-cites="vonhippel2007 west2014">(<a href="#ref-vonhippel2007" role="doc-biblioref">Von Hippel 2007</a>; <a href="#ref-west2014" role="doc-biblioref">West et al. 2014</a>)</span>. Many of these OSS projects represent an open network of innovation communities and bear similarities to more formal strategic alliances aimed at sharing costs and bringing external expertise to the project <span class="citation" data-cites="taherizadeh2019">(<a href="#ref-taherizadeh2019" role="doc-biblioref">Taherizadeh and Isabelle 2019</a>)</span>. However, strategic alliances are typically governed by contractual or equity obligations, while OSS commonly uses non-binding social commitments and does not aim to control knowledge spillovers due to their open nature. In their analysis of 124 firms, <span class="citation" data-cites="gassmann2004">Gassmann and Enkel (<a href="#ref-gassmann2004" role="doc-biblioref">2004</a>)</span> suggested that coupled processes were used by firms to set standards or to dominate the future development of new technology. These firms were able to improve their competitive position and minimize risks when they were able to balance the give-and-take of their collaborative relationships, requiring the capability to both absorb and externalize new knowledge. Interestingly, some corporations have aimed to combine open innovation networks and formal strategic alliances by creating formal arrangements with informal innovation hubs, blurring the distinction between these two innovation strategies <span class="citation" data-cites="shaikh2019">(<a href="#ref-shaikh2019" role="doc-biblioref">Shaikh and Levina 2019</a>)</span>.</p>
<div id="fig-structural_approach" class="lightbox quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-structural_approach-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/Innovation-Structures.excalidraw.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2"><img src="images/Innovation-Structures.excalidraw.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-structural_approach-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Structural approach to software development. Modified based on <span class="citation" data-cites="west2006">West and Gallagher (<a href="#ref-west2006" role="doc-biblioref">2006</a>)</span>
</figcaption>
</figure>
</div>
<p>For example, the popular open-source operating system Linux <span class="citation" data-cites="linux">(<a href="#ref-linux" role="doc-biblioref">Torvalds 1991</a>)</span>, which Linus Torvalds started as a hobby project, was initially developed by a community of individual developers. Today, the Linux project is formalized into an independent foundation and receives contributions from individuals and over 200 corporations alike <span class="citation" data-cites="ahmad2021">(<a href="#ref-ahmad2021" role="doc-biblioref">Ahmad 2021</a>)</span>, making it a community of corporate and individual contributors. This corporate involvement goes beyond code contributions and includes community building and project governance <span class="citation" data-cites="bonaccorsi2007">(<a href="#ref-bonaccorsi2007" role="doc-biblioref">Bonaccorsi et al. 2007</a>)</span>.</p>
<p>Next to co-creating OSS projects within a network, some firms may decide to open-source internal software to the public. This <em>inside-out</em> transformation of internal intellectual properties (IP) can aim to lower development cost <span class="citation" data-cites="west2006">(<a href="#ref-west2006" role="doc-biblioref">West and Gallagher 2006</a>)</span>. However, corporate control over the future direction of the software is often tightly maintained within these transformations <span class="citation" data-cites="west2006 west2014 vanhaverbeke2006">(<a href="#ref-west2006" role="doc-biblioref">West and Gallagher 2006</a>; <a href="#ref-west2014" role="doc-biblioref">West et al. 2014</a>; <a href="#ref-vanhaverbeke2006" role="doc-biblioref">Vanhaverbeke 2006</a>)</span>. This control does not necessarily require ownership as firms can donate their IP to an independent foundation, giving up formal control over the project while remaining a dominating contributor and steering the direction of the project <span class="citation" data-cites="honeypot2022 zhang2020a">(<a href="#ref-honeypot2022" role="doc-biblioref">Honeypot 2022</a>; <a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>)</span>.</p>
<p>At last, <em>outside-in</em> innovation processes in the context of OSS are often aimed at bringing in software developed by independent developers or other corporations. Specifically, firms might ‘free ride’ on existing OSS projects to support their internal software ecosystem, building on top of industry-validated and proven software <span class="citation" data-cites="kumar2011">(<a href="#ref-kumar2011" role="doc-biblioref">Kumar, Gordon, and Srinivasan 2011</a>)</span>. For example, many firms are utilizing smaller open-source projects maintained by only a few independent developers to support crucial infrastructure or network security <span class="citation" data-cites="silic2016">(<a href="#ref-silic2016" role="doc-biblioref">Silic and Back 2016</a>)</span>. These firms rely on community contributors or other organizations to fix software bugs or security issues within these OSS.</p>
<p>In their paper, <span class="citation" data-cites="vanhaverbeke2008">Vanhaverbeke, Vrande, and Chesbrough (<a href="#ref-vanhaverbeke2008" role="doc-biblioref">2008</a>)</span> argued that some firms may use OSS to cope with innovation risks and uncertainty by making small investments to create options for the company. Specifically, firms may contribute small amounts to a project without fully integrating the software into their business. Should the uncertainty or risk decrease, the firm can increase its involvement through subsequent investments. This maintains the option for a delayed commitment to the project and enables bringing innovations into the firm without excessive risks.</p>
<p>Overall, these open innovation strategies aim to exploit internal innovation, bring in external knowledge, and motivate outsiders to contribute to the firm’s projects. Interestingly, some but not all of these OSS communities are leveraged to sell innovations as products or services <span class="citation" data-cites="west2008">(<a href="#ref-west2008" role="doc-biblioref">West and Lakhani 2008</a>)</span>. For example, <span class="citation" data-cites="vonhippel2007">Von Hippel (<a href="#ref-vonhippel2007" role="doc-biblioref">2007</a>)</span> found that some OSS projects are examples of innovation networks consisting only of users, defined as individuals or organizations that use but do not sell their innovations. Within these horizontal networks, users drive innovation development, production, distribution, and consumption. <span class="citation" data-cites="vonhippel2007">Von Hippel (<a href="#ref-vonhippel2007" role="doc-biblioref">2007</a>)</span> identified three conditions necessary for the development of these horizontal user innovation networks: (1) Some users are willing to innovate, (2) some users freely reveal their innovations, and (3) users can manufacture their innovations at a low cost.</p>
<p>These conditions align with the qualitative investigation by <span class="citation" data-cites="butler2021">Butler et al. (<a href="#ref-butler2021" role="doc-biblioref">2021</a>)</span>, who looked at the different modes of corporate contribution and collaboration. The authors conducted multiple interview studies with companies and their employees who contributed to OSS projects to understand the underlying motivations. Most interviewees noted that the business benefits for firms were often more than the creation of software but also included the acquisition of knowledge, skills, and broader organizational learnings. The author reported that a core motivation for firms was to maintain the sustainability of OSS projects which are crucial but non-differentiating. Thus, firms’ products might integrate or depend on external OSS projects but are not perceived as generating value for the business, broadly agreeing with the <span class="citation" data-cites="vonhippel2007">Von Hippel (<a href="#ref-vonhippel2007" role="doc-biblioref">2007</a>)</span> required three conditions of horizontal user innovations.</p>
<p>However, the interviewees also reported other forms of contribution beyond additions to the project’s source code. This included membership on steering committees, financial contributions, project governance, and community building. Thus, aligning more closely to the ideas of open innovation communities, which include identity, memberships, and loyalty, than horizontal user networks <span class="citation" data-cites="west2008">(<a href="#ref-west2008" role="doc-biblioref">West and Lakhani 2008</a>)</span>. Although <span class="citation" data-cites="vonhippel2007">Von Hippel (<a href="#ref-vonhippel2007" role="doc-biblioref">2007</a>)</span> states that user networks can be part of communities, it does suggest that firms may have two distinct motivations and processes when engaging in OSS development: (1) A coupled innovation process to develop or maintain non-differentiating software and (2) an inside-out approach to creating new markets, set standards or product designs. This second approach would require the firm to maintain significant control over the OSS project, resulting in fewer collaborations. Either through direct project governance or through a dominant amount of code contribution.</p>
<section id="hypothesis-1-control-through-domination" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-1-control-through-domination">Hypothesis 1: Control Through Domination</h2>
<p>A firm might aim to be a dominating contributor within an OSS project to maintain control and steer the innovation process, enabling the organization to control the in-flow and out-flow of innovation. In contrast, other firms might be less inclined to collaborate with competitors in these scenarios as there might lose control of their OSS contributions. Some evidence for this theory comes from a study by <span class="citation" data-cites="oneil2022">O’Neil et al. (<a href="#ref-oneil2022" role="doc-biblioref">2022</a>)</span> who demonstrated selective cooperation of companies within OSS projects. In their analysis of 135 projects on the popular open-source platform GitHub, the authors identified non-overlapping contribution territories among major technology companies. Specifically, contributions from Google employees were close to zero for projects in which Microsoft was the dominant project contributor. However, one can question to which extent this can be generalized outside these two main technology firms and if smaller firms might be more open to directly cooperating with rivals on OSS. Further, smaller firms might be incentivised to collaborate with dominant large cooperations on OSS projects to utilize the innovation resources of their bigger partner.</p>
<p>A more quantitative perspective on the same questions comes from <span class="citation" data-cites="zhang2022">Zhang, He, and Zhou (<a href="#ref-zhang2022" role="doc-biblioref">2022</a>)</span> who investigated the OpenStack ecosystem, a collection of thousands of individual OSS projects. This network of projects, mostly maintained and developed by firms, contains a wide range of software aimed at cloud computing technologies. The authors find that while most companies collaborate with others, the contribution network is centered around a few large IT companies. Not surprisingly, these central firms are also one of the most productive contributors to this ecosystem and are often dominating individual projects. The authors link this behavior as part of several strategies firms employ; this includes firms that provide a full set of comprehensive software as part of their consultancy or services solutions and those which are part of a horizontal network of users who use OpenStack in their own business. This quantitative analysis can be seen as supporting both coupled and inside-out approaches to OSS contribution and collaboration. However, the authors did not explore the correlation between dominating behavior and project collaboration. Furthermore, it is worth considering the extent to which OpenStack represents the broader OSS landscape, given its exclusive focus on cloud computing and lack of inclusion of a diverse range of other projects.</p>
<p>Overall, past research has found a significant degree of corporate collaboration within OSS projects with single firms often dominating and controlling the projects <span class="citation" data-cites="zhang2022 schaarschmidt2015">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-schaarschmidt2015" role="doc-biblioref">Schaarschmidt, Walsh, and von Kortzfleisch 2015</a>)</span>. One can hypothesize that the domination of a single actor can lead to fewer contributions by other firms due to the assumed lack of control and dependence on a potential competitor. Interestingly, this pattern is also observed on the individual software developer level in which the majority of code is often only produced by a few individuals <span class="citation" data-cites="hawkins2004">(<a href="#ref-hawkins2004" role="doc-biblioref">Hawkins 2004</a>)</span>. This suggests that while these projects remain open to all to contribute, others are not incentivized to join. Both <span class="citation" data-cites="zhang2022">Zhang, He, and Zhou (<a href="#ref-zhang2022" role="doc-biblioref">2022</a>)</span> and <span class="citation" data-cites="hawkins2004">Hawkins (<a href="#ref-hawkins2004" role="doc-biblioref">2004</a>)</span> remain descriptive in their analysis of dominating OSS developers and have not quantitatively tested if the dominant contribution behaviors of one firm will lower the incentives of others to contribute.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Hypothesis 1: Control Through Domination">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hypothesis 1: Control Through Domination
</div>
</div>
<div class="callout-body-container callout-body">
<p>OSS projects in which a single firm dominates will have fewer collaborating partners</p>
</div>
</div>
</section>
<section id="hypothesis-2-control-through-licenses" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-2-control-through-licenses">Hypothesis 2: Control through Licenses</h2>
<p>Transaction cost economic theory (TCE) suggests that firms choose different forms of governance modes to minimize transaction costs given the threat of spillovers and opportunism when working with others <span class="citation" data-cites="williamson1975">(<a href="#ref-williamson1975" role="doc-biblioref">Williamson 1975</a>)</span>. These transaction costs are the resources that must be spent to complete a transaction. This includes, for example, the cost before the transactions, such as drafting of contracts or negotiating, and subsequent costs, such as setup or running costs, maladaptation costs, and others. TCE suggests that firms adopt either a market or hierarchical organization to adapt to this perceived transaction costs <span class="citation" data-cites="hsieh2016">(<a href="#ref-hsieh2016" role="doc-biblioref">Hsieh, Huang, and Lee 2016</a>)</span>. Thus, companies may use efficient price mechanisms on the open market to coordinate between innovation collaborators (market organization) or utilize internal hierarchical structures within the company boundaries (hierarchical organization) to control spillovers. The transaction cost of a product or service is influenced by the assets’ specificity, uncertainty, and transaction frequency <span class="citation" data-cites="williamson1975 williamson1985 williamson2010">(<a href="#ref-williamson1975" role="doc-biblioref">Williamson 1975</a>, <a href="#ref-williamson1985" role="doc-biblioref">1985</a>, <a href="#ref-williamson2010" role="doc-biblioref">2010</a>)</span>. <span class="citation" data-cites="williamson1985">(<a href="#ref-williamson1985" role="doc-biblioref">Williamson 1985</a>)</span> defined the most critical component, asset specificity, as the degree to which assets are specialized for a specific transaction, making it costly to use for other purposes.</p>
<p>TCE has been applied outside of OI with great success <span class="citation" data-cites="williamson1985">(<a href="#ref-williamson1985" role="doc-biblioref">Williamson 1985</a>)</span>, but the application of the theory to the OI phenomenon has been viewed critically by others <span class="citation" data-cites="vanhaverbeke2014 remneland-wikhamn2012">(<a href="#ref-vanhaverbeke2014" role="doc-biblioref">Vanhaverbeke and Cloodt 2014</a>; <a href="#ref-remneland-wikhamn2012" role="doc-biblioref">Remneland-Wikhamn and Knights 2012</a>)</span>. For example, TCE suggests that transaction cost increases when dealing with non-trusted and potentially opportunistic market participants. To manage this behavioral uncertainty, firms can adopt more control through licenses, thus aiming to reduce tension and lowering spillovers.</p>
<p>Empirical evidence on this comes from <span class="citation" data-cites="oxley1997">Oxley (<a href="#ref-oxley1997" role="doc-biblioref">1997</a>)</span>, who showed in their analysis of governance modes in strategic alliances that firms commonly adopt more hierarchical forms in the presence of weak intellectual property rights. Similar results were also shown in other studies in the US automotive industry <span class="citation" data-cites="langlois1989">(<a href="#ref-langlois1989" role="doc-biblioref">Langlois and Robertson 1989</a>)</span> and the biopharmaceuticals industry <span class="citation" data-cites="gulati1998">(<a href="#ref-gulati1998" role="doc-biblioref">Gulati and Singh 1998</a>)</span>. However, applying TCE to OSS has focused mainly on the engagement of individual customers <span class="citation" data-cites="benkler2002 prahalad2004">(<a href="#ref-benkler2002" role="doc-biblioref">Benkler 2002</a>; <a href="#ref-prahalad2004" role="doc-biblioref">Prahalad and Ramaswamy 2004</a>)</span> or contributors from the community <span class="citation" data-cites="sawhney2005">(<a href="#ref-sawhney2005" role="doc-biblioref">Sawhney, Verona, and Prandelli 2005</a>)</span>. For example, <span class="citation" data-cites="benkler2002">Benkler (<a href="#ref-benkler2002" role="doc-biblioref">2002</a>)</span> suggested that the increased availability of digital tools and personal computing gives rise to new forms of ‘social production’ as an alternative to market-driven innovations. This view of TCE aligns with the early social-political ideas around OSS development <span class="citation" data-cites="debianfoundation2023 lerner2002">(<a href="#ref-debianfoundation2023" role="doc-biblioref">Debian Foundation 2023</a>; <a href="#ref-lerner2002" role="doc-biblioref">Lerner and Tirole 2002</a>)</span>, but has been increasingly questioned by the domination of company contributions to OSS projects <span class="citation" data-cites="zhang2020a">(<a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>)</span>. Indeed, qualitative <span class="citation" data-cites="ahmad2021 krishnamurthy2005 schaarschmidt2015">(<a href="#ref-ahmad2021" role="doc-biblioref">Ahmad 2021</a>; <a href="#ref-krishnamurthy2005" role="doc-biblioref">Krishnamurthy 2005</a>; <a href="#ref-schaarschmidt2015" role="doc-biblioref">Schaarschmidt, Walsh, and von Kortzfleisch 2015</a>)</span> and quantitative <span class="citation" data-cites="zhang2022 zhang2020a shaikh2019 stephens2021">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>; <a href="#ref-shaikh2019" role="doc-biblioref">Shaikh and Levina 2019</a>; <a href="#ref-stephens2021" role="doc-biblioref">Stephens 2021</a>)</span> investigations on OSS development suggest instead a more traditional perspective of TCE in which firms collaborate actively in projects which are non-differentiating in nature and therefore of low specificity and uncertainty.</p>
<p>This is also reflected in a market-driven form of governance as the OSS development is open for new partners to join as the market sets the overall transaction cost. On the other hand, several companies have open-sourced software with potential commercial value as a way to set standards and create a new market while maintaining control through licenses and other forms of governance <span class="citation" data-cites="lerner2002 ahmad2021 zhang2022">(<a href="#ref-lerner2002" role="doc-biblioref">Lerner and Tirole 2002</a>; <a href="#ref-ahmad2021" role="doc-biblioref">Ahmad 2021</a>; <a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>)</span>, therefore increasing specificity.</p>
<p>In their study of 250 Chinese start-ups in electronic and IT, for example, <span class="citation" data-cites="hsieh2016">Hsieh, Huang, and Lee (<a href="#ref-hsieh2016" role="doc-biblioref">2016</a>)</span> empirically showed that firms with high specificity and behavioral uncertainty adopted more elevated levels of internal governance but engaged in open-innovation strategies to commercialize their products or services. Similar observations have been made by other authors who described tighter control mechanisms for open-source projects developed by individual companies in the form of steering committees, dominating code contributions, or other forms of controls <span class="citation" data-cites="zhang2022 schaarschmidt2015">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-schaarschmidt2015" role="doc-biblioref">Schaarschmidt, Walsh, and von Kortzfleisch 2015</a>)</span>.</p>
<p>One way firms commonly implement hierarchical controls in OSS is through licenses. OSS licenses are significantly less restrictive than their commercial equivalent as they allow direct access to the underlying source code, can be freely distributed, and allow anyone to create derivative work. Despite these shared principles, OSS licenses vary significantly to what extent they can be used within commercial software <span class="citation" data-cites="sen2008b">(<a href="#ref-sen2008b" role="doc-biblioref">Sen, Subramaniam, and Nelson 2008</a>)</span>. Licenses categorized as ‘copyleft’ require that all derivative work be published under a license that offers the same rights, making it not very attractive to commercial organizations. In contrast, ‘permissive’ licenses impose less restriction and only require attribution of the original author on all derivative works <span class="citation" data-cites="rosen2004">(<a href="#ref-rosen2004" role="doc-biblioref">Rosen 2004</a>)</span>. Some firms might even publish their software into the public domain, thus abstaining from imposing any form of license. Hence, the choice of an OSS license can be seen as a way to impose higher transaction costs and therefore represents a form of hierarchical control. Thus, one would expect that more restrictive licenses would lead to less collaboration.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Hypothesis 2: Control through Licenses">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hypothesis 2: Control through Licenses
</div>
</div>
<div class="callout-body-container callout-body">
<p>OSS projects with more restrictive licenses have fewer collaborators.</p>
</div>
</div>
</section>
<section id="hypothesis-3-collaborations-heterogeneity-and-productivity" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-3-collaborations-heterogeneity-and-productivity">Hypothesis 3: Collaborations heterogeneity and productivity</h2>
<p>Overall, TCE has been argued to be a sound theoretical framework to describe and understand OI <span class="citation" data-cites="vanhaverbeke2006 dahlander2010 vrande2010 bogers2011">(<a href="#ref-vanhaverbeke2006" role="doc-biblioref">Vanhaverbeke 2006</a>; <a href="#ref-dahlander2010" role="doc-biblioref">Dahlander and Gann 2010</a>; <a href="#ref-vrande2010" role="doc-biblioref">Vrande, Vanhaverbeke, and Gassmann 2010</a>; <a href="#ref-bogers2011" role="doc-biblioref">Bogers 2011</a>)</span>. However, the application of TCE on OI has not been without criticism. For example, <span class="citation" data-cites="vanhaverbeke2014">Vanhaverbeke and Cloodt (<a href="#ref-vanhaverbeke2014" role="doc-biblioref">2014</a>)</span> questioned firms’ desire to minimize transaction costs rather than maximize transaction value. Indeed, <span class="citation" data-cites="dyer1997">Dyer (<a href="#ref-dyer1997" role="doc-biblioref">1997</a>)</span> empirically showed within the automotive industry in the U.S.A. and Japan that firms are more focused on the total transaction value, that is, transaction value minus transaction cost. As a result, while transaction cost can increase with specificity, firms will choose their governance structure based on the total value of the transaction and not exclusively on price <span class="citation" data-cites="zajac1993">(<a href="#ref-zajac1993" role="doc-biblioref">Zajac and Olsen 1993</a>)</span>. This can potentially explain the lack of hierarchical controls in many open-source projects and would suggest two distinct types of OSS projects: Those dominated and controlled by a single firm and those that develop software with less hierarchical structures but more equal contributions.</p>
<p><span class="citation" data-cites="demil2006">Demil and Lecocq (<a href="#ref-demil2006" role="doc-biblioref">2006</a>)</span> suggested that the latter form might result in productivity gains for associated firms through lower transaction costs caused by sharing a single open-source contract among contributors and less uncertainty via a more significant number of available partners. Thus, firms might choose to lower transaction costs to facilitate productive and collaborative code development with an expanded set of collaborators, ultimately increasing transaction value. Indeed, previous research showed that diversity and distribution of code contributors are significantly associated with productivity in OSS projects <span class="citation" data-cites="izquierdo2019 vasilescu2015 lerner2002 tan2007">(<a href="#ref-izquierdo2019" role="doc-biblioref">Izquierdo et al. 2019</a>; <a href="#ref-vasilescu2015" role="doc-biblioref">Vasilescu et al. 2015</a>; <a href="#ref-lerner2002" role="doc-biblioref">Lerner and Tirole 2002</a>; <a href="#ref-tan2007" role="doc-biblioref">Tan, Mookerjee, and Singh 2007</a>)</span>. In contrast, projects with only a few corporate contributors might benefit from reaching faster consensus and a simplified governance structure, thus increasing transaction value through fewer but more strategically aligned collaborators <span class="citation" data-cites="fjeldstad2012">(<a href="#ref-fjeldstad2012" role="doc-biblioref">Fjeldstad et al. 2012</a>)</span>.</p>
<p>Consequently, projects that fall in the middle of this spectrum might suffer from higher transaction costs and lower productivity through a limited quantity of developers. Conclusively, one would hypothesize a U-Shaped relationship between collaboration heterogeneity and productivity in OSS projects.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Hypothesis 3: Collaborations heterogeneity and productivity">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hypothesis 3: Collaborations heterogeneity and productivity
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is a U-Shape relationship between collaboration heterogeneity and project productivity.</p>
</div>
</div>
</section>
<section id="hypothesis-4-collaboration-networks" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-4-collaboration-networks">Hypothesis 4: Collaboration Networks</h2>
<p>While firms utilize different mechanisms to control OSS projects, some organizations might also aim to attract collaborators to reduce costs and bring external knowledge and resources into the innovation project <span class="citation" data-cites="chesbrough2006">(<a href="#ref-chesbrough2006" role="doc-biblioref">Chesbrough and Crowther 2006</a>)</span>. <span class="citation" data-cites="dyer1998">(<a href="#ref-dyer1998" role="doc-biblioref">Dyer and Singh 1998</a>)</span> noted that this requires an investment in relationships capable of developing and combining internal and external resources.</p>
<p>These relationships can be seen as resources for the company which can be utilized to form competitive advantages according to the resource-based view (RBV) theory of the firm <span class="citation" data-cites="vanhaverbeke2014 barney1991a">(<a href="#ref-vanhaverbeke2014" role="doc-biblioref">Vanhaverbeke and Cloodt 2014</a>; <a href="#ref-barney1991a" role="doc-biblioref">Barney 1991</a>)</span>. This perspective assumes that a firm requires a unique set of difficult-to-imitate resources that are valuable, rare, and inimitable (VRI) <span class="citation" data-cites="grant1991 barney1991a">(<a href="#ref-grant1991" role="doc-biblioref">Grant 1991</a>; <a href="#ref-barney1991a" role="doc-biblioref">Barney 1991</a>)</span>. Traditionally, this view is more aligned with a closed form of innovation in which firms only innovate inside their boundaries and do not transfer knowledge to the outside. However, valuable resources can also be found outside the firm’s boundary, and companies capable of combining those uniquely can generate a competitive advantage. As such, these relationships can be seen as rent-extracting resources not available to those outside the relationship, providing a valuable RVB perspective on OI and OSS processes <span class="citation" data-cites="vanhaverbeke2014">(<a href="#ref-vanhaverbeke2014" role="doc-biblioref">Vanhaverbeke and Cloodt 2014</a>)</span>.</p>
<p>Instead of focusing solely on a single resource, this view can be expanded by examining a collection of resources as the unit of analysis. In their empirical and simulation study <span class="citation" data-cites="alexy2018">Alexy et al. (<a href="#ref-alexy2018" role="doc-biblioref">2018</a>)</span> showed that in both monopolistic and duopolistic situations, open innovation strategies could increase profits through complementary effects with other resources. Specifically, firms could offer complementary products or services as part of their OI while simultaneously lowering their fixed cost by jointly producing resource bundles with others <span class="citation" data-cites="helfat2003">(<a href="#ref-helfat2003" role="doc-biblioref">Helfat and Peteraf 2003</a>)</span>. For example, a company might open-source software with no clear competitive advantage to coordinate collaborative development with others to provide proprietary complements to the market. Making resources available to the public can also serve as a useful tool for organizations to attract top talent, enhance their brand reputation, and cultivate intangible assets. Overall, firms which were able to reduce their fixed cost through utilizing their network of resources and relationships were able to generate a sustained competitive advantage <span class="citation" data-cites="alexy2018">(<a href="#ref-alexy2018" role="doc-biblioref">Alexy et al. 2018</a>)</span>. Some additional evidence of this comes from a study by <span class="citation" data-cites="singh2011">Singh, Tan, and Mookerjee (<a href="#ref-singh2011" role="doc-biblioref">2011</a>)</span>, who showed that the number of internal and external contacts of developers are significant predictors for project success within a panel of 2,378 projects.</p>
<p>However, firms that cannot reduce their fixed cost while opening up their innovations to others might be in danger of reducing their profits or destroying the whole market entirely. A practical example of a real-world scenario comes from Netscape’s attempt to undercut Microsoft’s internet browsers by open-sourcing their competing product. This did little to reduce the firm’s cost and did not utilize a sufficient number of complementary products, destroying the market for paid desktop browsers through free offerings in the process <span class="citation" data-cites="windrum2004 wang2005b">(<a href="#ref-windrum2004" role="doc-biblioref">Windrum 2004</a>; <a href="#ref-wang2005b" role="doc-biblioref">Wang, Wu, and Lin 2005</a>)</span>. Thus, RBV shows similarity in OSS development with razor-blade business models in which control over one resource is given up in exchange for control of another <span class="citation" data-cites="abdelkafi2013 tripsas2000">(<a href="#ref-abdelkafi2013" role="doc-biblioref">Abdelkafi, Makhotin, and Posselt 2013</a>; <a href="#ref-tripsas2000" role="doc-biblioref">Tripsas and Gavetti 2000</a>)</span>. This type of innovation also seems to impact the overall market capitalization of the firm. <span class="citation" data-cites="liu2022">Liu, Lai, and He (<a href="#ref-liu2022" role="doc-biblioref">2022</a>)</span> showed in their analysis of 132 Chinese firms that participation within a firm’s innovation network and network size were significant predictors of market value, suggesting that these relationships can be seen as intangible assets.</p>
<p>These network effects can also attract furthermore firms that may want to utilize the firm’s network value. Smaller firms might consider the degree of existing relationships and networks when choosing a larger partner to collaborate with <span class="citation" data-cites="degroote2020 singh2011">(<a href="#ref-degroote2020" role="doc-biblioref">De Groote and Backmann 2020</a>; <a href="#ref-singh2011" role="doc-biblioref">Singh, Tan, and Mookerjee 2011</a>)</span>. Indicating that the bundle of available resources of the main OSS contributor can be an attractive factor for future collaboration with others. Specifically, by collaborating with high network-value partners, firms will be able to utilize the relationships of the main contributors, enabling smaller firms to establish valuable partnerships and therefore extracting rent from this relationship <span class="citation" data-cites="lin2008">(<a href="#ref-lin2008" role="doc-biblioref">Lin 2008</a>)</span>. Unfortunately, previous research has only paid little attention to the ability of a firm’s network value to attract similar partners. An exception is <span class="citation" data-cites="casalo2009">Casaló et al. (<a href="#ref-casalo2009" role="doc-biblioref">2009</a>)</span>, who showed in their analysis of 215 OSS developers that the reputation of the main contributing firm plays a significant role in attracting new developers to the project. However, previous research has not systemically evaluated to what extent these network effects can attract corporate collaborations.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Hypothesis 4: Collaboration Networks">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hypothesis 4: Collaboration Networks
</div>
</div>
<div class="callout-body-container callout-body">
<p>OSS projects which have high network-value contributors will attract more collaborators</p>
</div>
</div>
</section>
<section id="hypothesis-5-interaction-between-contribution-intensity-and-network-value" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-5-interaction-between-contribution-intensity-and-network-value">Hypothesis 5: Interaction between contribution intensity and network-value</h2>
<p>As RBV suggests that two firms may weight their strategic importance to maintain control over the same resource differently depending on the composition of their resource bundle. Thus, some firms may desire to control a focal resource to utilize their unique resource bundle, while another firm may consider the same resource only as a small part of their broader resource bundle (<a href="#fig-resource_bundles" class="quarto-xref">Figure&nbsp;3</a>). This potentially explains why direct competitors are less likely to engage in the co-production of OSS software and why some firms will dominate specific OSS projects while contributing to others only sporadically <span class="citation" data-cites="zhang2022">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>)</span>. Similarly, <span class="citation" data-cites="dyer1997">Dyer (<a href="#ref-dyer1997" role="doc-biblioref">1997</a>)</span> noted that partners who bring a higher percentage and more critical resources within the partnership could also extract a higher proportion of the rent. So far, this interdependency and power structure within the OSS network has only received little attention from the academic literature <span class="citation" data-cites="vanhaverbeke2014">(<a href="#ref-vanhaverbeke2014" role="doc-biblioref">Vanhaverbeke and Cloodt 2014</a>)</span>.</p>
<div id="fig-resource_bundles" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resource_bundles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/bundle-overlap.excalidraw.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resource_bundles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Firms contributing to different projects based on importance
</figcaption>
</figure>
</div>
<p>An exception is <span class="citation" data-cites="demontalvo2004">de Montalvo, van de Kar, and Maitland (<a href="#ref-demontalvo2004" role="doc-biblioref">2004</a>)</span>, who showed that telecommunication network operators in Japan, the U.S.A., and Europe control the overall value network by contributing unique resources. In their analysis, the authors categorized resources into essential, network-specific, and generic categories. Thus, firms that contributed resources to the first category could gain the most control within the network. In the context of OSS development, this raises the question if firms can control the development through essential resources beyond the simple quantity of code contributions. These additional resources could be tangible, like access to unique data, or intangible, such as brand or human resources.</p>
<p>However, the lack of control implies that firms may become dependent on their network of contributing firms and therefore are required to manage the associated risks, such as a change in the strategic direction of the controlling firm. While <span class="citation" data-cites="pfeffer1978">(<a href="#ref-pfeffer1978" role="doc-biblioref">Pfeffer and Salancik 1978</a>)</span> suggested that firms will avoid this dependency and aim to establish the required control, most firms in OSS will only contribute generic resources, such as code, which others can easily replace. Thus, firms may perceive the lack of control as a manageable risk as resources can easily be replaced by others or themselves for OSS, which are replaceable in their value generation. Hence, smaller firms may be attracted to utilize resources controlled by larger enterprises as they are often not direct competitors and can more easily provide generic resources, such as code contributions, managing their perceived risk with a strong partner.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Hypothesis 5: Interaction between contribution intensity and network-value">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hypothesis 5: Interaction between contribution intensity and network-value
</div>
</div>
<div class="callout-body-container callout-body">
<p>Projects dominated by a firm with a high number of contributors will attract more collaborators than a dominating company with few contributors.</p>
</div>
</div>
</section>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>GitHub is a popular platform for software developers that allows individuals and teams to work together on software by providing a centralized location for code repositories, issue tracking, project management, and collaboration tools <span class="citation" data-cites="githubinc.2023">(<a href="#ref-githubinc.2023" role="doc-biblioref">GitHub Inc. 2023</a>)</span>. The platform has seen significant growth over the last ten years (<a href="#fig-repo_growth" class="quarto-xref">Figure&nbsp;1</a>) and can be considered the most popular and largest code hosting platform worldwide. GitHub is particularly popular among open-source developers, despite being owned by Microsoft, which acquired the platform in 2018 <span class="citation" data-cites="greene2018">(<a href="#ref-greene2018" role="doc-biblioref">Greene 2018</a>)</span>.</p>
<p>All projects on GitHub use the version control system Git to track code changes in projects and enable collaboration. Each time a developer changes a set of files, they have to create a <em>commit</em> which captures the changes along with a commit message, author’s login name, email address, and time stamp <span class="citation" data-cites="zhang2021">(<a href="#ref-zhang2021" role="doc-biblioref">Zhang et al. 2021</a>)</span>. These meta-data are publicly available to analyze and can be accessed directly through Application Programming Interfaces (APIs) or databases such as Google’s Big Query <span class="citation" data-cites="octolab_gharchive">(<a href="#ref-octolab_gharchive" role="doc-biblioref">OctoLab 2021</a>)</span>. In addition, each project can also be associated with various meta-data such as creation date, license, number of reported issues, and number of users who bookmarked the software. GitHub also tracks the number of copies users have created on the platform for each project, also called ‘forks’.</p>
<section id="collecting-and-filtering" class="level3">
<h3 class="anchored" data-anchor-id="collecting-and-filtering">Collecting and Filtering</h3>
<p>In order to facilitate the project-level analysis of corporate collaboration, I have acquired all developer commits from 2022 in code repositories that have a minimum of 100 bookmarks. Less popular repositories were removed to ensure that only projects were considered which were original and not copies of already existing code repositories. This resulted in a total of <span class="math inline">\(3,252,893\)</span> commits from <span class="math inline">\(15,654\)</span> projects being considered for further analysis.</p>
<p>Like other studies, I excluded commits to projects associated with automated bots <span class="citation" data-cites="zhang2022 erlenhov2019">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-erlenhov2019" role="doc-biblioref">Erlenhov et al. 2019</a>)</span>. These bots perform everyday housekeeping tasks within these projects, such as automatically updating software dependency or preparing new releases. While these bots can be counted towards a firm’s overall code contributions, the increased quantity of code can inflate the importance of individual organizations or affect the interpretation of the results. Thus, bots were first identified by matching either the username or email address of commits with commonly used bot names, such as ‘Bot’, ‘Automation’, or ‘GitHub Action’, and then removed from the dataset.</p>
<p>Projects with less than two collaborators and less than 100 commits over the year were also excluded from the analysis as the limited activity of these projects might have biased the results towards characteristics of inactive projects. After these steps, a total of <span class="math inline">\(1,127\)</span> projects remained with <span class="math inline">\(1,517,498\)</span> code commits in total.</p>
</section>
<section id="identification-of-developer-affiliation" class="level3">
<h3 class="anchored" data-anchor-id="identification-of-developer-affiliation">Identification of Developer Affiliation</h3>
<p>To estimate the contribution of each firm to individual OSS projects, one needs to attribute each commit to a user and their employer. However, developers’ affiliations are not included in the meta-data and need to be derived based on user-name and email addresses. For example, if a developer’s email address domain were ‘ch.ibm.com’ or ‘de.ibm.com’, their affiliation would be classified as IBM (see <a href="#tbl-affiliation_example" class="quarto-xref">Table&nbsp;1</a> for examples). Interestingly, firms often reflect their employees’ hierarchical structures or geographical locations within their email domains. This makes the association of email domains with organizational entities more challenging. To support matching email domains with organizations, I have utilized 325 crowdsourced email domain patterns by the Open Source Contributor Index (OSCI), a project which aims to track and measure OSS development on GitHub <span class="citation" data-cites="epamsystems2023">(<a href="#ref-epamsystems2023" role="doc-biblioref">EPAM Systems 2023</a>)</span>. These patterns represent a non-exhaustive list of the biggest open-source contributing companies and their associated email domains. As most organizational OSS contributors are from the technology industry, I further narrowed down the affiliated domain patterns to 267 technology firms within this list. Code commits that could not be affiliated with any company were discarded from the analysis. Out of 267 technology companies, 237 were found to be active on GitHub during the investigation period.</p>
<div id="tbl-affiliation_example" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-affiliation_example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Examples of developer affiliations based on email addresses
</figcaption>
<div aria-describedby="tbl-affiliation_example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">User Name</th>
<th style="text-align: left;">Email Address</th>
<th style="text-align: left;">Affiliation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alex Halorado</td>
<td style="text-align: left;">d1bbfd851efd451b402ce3429acab778b9b64dc2@elastic.co</td>
<td style="text-align: left;">Elastic</td>
</tr>
<tr class="even">
<td style="text-align: left;">Michael Micht</td>
<td style="text-align: left;">adf2668dc4269e7975f009ac8ef1a5765fd3ef1d@microsoft.com</td>
<td style="text-align: left;">Microsoft</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tian Ho</td>
<td style="text-align: left;">ee4d4d946a16706035a4754f9504dccb256d@alibaba-inc.com</td>
<td style="text-align: left;">Alibaba</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="data-processing" class="level2">
<h2 class="anchored" data-anchor-id="data-processing">Data Processing</h2>
<p>The extracted data on each project, user, and code commit were further processed to characterize organizations’ contributions in more detail.</p>
<section id="sssection:network-value" class="level3">
<h3 class="anchored" data-anchor-id="sssection:network-value">Firm’s Network Value</h3>
<p>One can compute the relative importance of an organization to the overall open-source community by measuring how central the organization is positioned within this network of OSS contributors. For example, a firm that is actively contributing to several popular projects with numerous collaborators can be considered to be more influential than a firm with only a few contributions. To represent this network, I counted the number of open-source software projects that each organization (network node) is partnering with other organizations on. The weight of a network edge, or connection between firms, signifies the frequency with which an organization collaborates with another on projects. For example, should both organization <em>A</em> and <em>B</em> contribute to project <span class="math inline">\(\Gamma\)</span> and <span class="math inline">\(\Theta\)</span>, then these two network nodes are linked with an edge weight of <span class="math inline">\(2\)</span>.</p>
<p>The network centrality of a given firm, or network node, can be derived through multiple measures, each capturing different aspects of importance <span class="citation" data-cites="newman2010">(<a href="#ref-newman2010" role="doc-biblioref">Newman 2010</a>)</span>. Within this analysis, I have used <em>degree centrality</em>, a standardized measure of the number of edges a node has within a network. This metric was then normalized by dividing by the maximum possible number of unique possible edges <span class="math inline">\(n-1\)</span>, in which <span class="math inline">\(n\)</span> is the number of nodes in the graph, expressing each organization’s centrality relative to the overall network size. To further aid interpretation in a regression analysis, one can further multiply the value by <span class="math inline">\(100\)</span> to express <em>degree centrality</em> as a percentage of maximum possible edges. Overall, the value captures how well-connected an organization is to the broader open-source community.</p>
<p>There are several other potential measurements of network centrality, such as <em>eigenvector centrality</em> and <em>betweenness centrality</em>. However, while both of these alternative methods can potentially capture the total influence of a firm more holistically by also taking the network importance of neighboring nodes into account, it introduces additional complexity in downstream analysis. Specifically, these measures would potentially induce endogeneity in predicting the number of project collaborators as network centrality measures would be at least partially derived from the dependent variable. To limit this potential bias, this analysis will use this more limited form of centrality measurement.</p>
<p>On a project level, this analysis is interested in which degree the centrality of the largest contributor affects the number of project collaborators. Hence, the variable <em>centrality</em> represents the network centrality of the firm that has contributed the most code commits to a respective OSS project.</p>
</section>
<section id="project-characteristics" class="level3">
<h3 class="anchored" data-anchor-id="project-characteristics">Project Characteristics</h3>
<p>The most interesting variable within this analysis is the number of firms contributing to an OSS project. As each commit author is associated with an organization, one can easily count the number of firms collaborating within a single project and their relative contribution to the project based on their total code commits. This relative contribution, or <em>intensity</em>, can further indicate the degree to which a firm dominates an OSS project. <em>Intensity</em> was computed according the approach established by <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>, which is defined as <span class="math display">\[\mbox{Intensity}^P = \max (\frac{\mbox{Commits}^P_C}{\mbox{Commits}^P}) \times 100\]</span> in which <span class="math inline">\(\mbox{Intensity}^P\)</span> is the largest proportion of commits by a company <span class="math inline">\(C\)</span> relative to the total number of project commits <span class="math inline">\(P\)</span>. Thus, intensity characterizes the degree of domination by the firm contributing the most.</p>
<p>In addition, <em>GitHub</em> also provides several project characteristics which can be used to isolate the effects of interest. These controlling variables include the age, size, number of bookmarks, number of reported issues, and number of project copies (‘forks’). These variables help account for the popularity and quality of a project which might influence developers’ desire to contribute to the project.</p>
</section>
<section id="oss-project-license" class="level3">
<h3 class="anchored" data-anchor-id="oss-project-license">OSS Project License</h3>
<p>A project’s license is an integral part of an OSS project as it governs how much others can reuse and modify the source code, potentially significantly affecting a firm’s decision to contribute to the project. This license information is recorded through a standardized format called the software package data exchange (SPDX) which contains a list of 512 OSS licenses <span class="citation" data-cites="spdx2023">(<a href="#ref-spdx2023" role="doc-biblioref">SPDX 2023</a>)</span>. As part of GitHub’s metainformation, license information on each project was extracted, resulting in <span class="math inline">\(42\)</span> unique identified licenses. Licenses were then classified into ‘copyleft’ or ‘permissive’ license. Projects which did not have any license were labeled to be in the public domain.</p>
</section>
<section id="project-contribution-heterogeneity" class="level3">
<h3 class="anchored" data-anchor-id="project-contribution-heterogeneity">Project Contribution Heterogeneity</h3>
<p>As the overall contributions and collaborations between firms are of central importance to this thesis, I also derived a measurement of contribution diversity for each project. Past research has used the Gini coefficient to observe the distribution of contributions within and across OSS projects <span class="citation" data-cites="zhang2021">(<a href="#ref-zhang2021" role="doc-biblioref">Zhang et al. 2021</a>)</span>. This frequently used metric is often applied to measure income inequality in an econometric context but also has been used in other areas. However, the Gini coefficient is well known to be downward biased in smaller populations and, as such problematic to measure distributions of firms’ contributions in smaller OSS projects with limited participants. As an alternative approach, this thesis will use the Simpson Diversity Index (SDI) to measure the relative heterogeneity in firms’ contributions <span class="citation" data-cites="simpson1949">(<a href="#ref-simpson1949" role="doc-biblioref">Simpson 1949</a>)</span>. This index is commonly used to investigate the concentration degree of species within an ecosystem. In the context of OSS projects, the metric can be interpreted as the probability that if one selects two developers randomly within the same projects, they are from different companies. The measure equates to: <span class="math display">\[D = 1 - \sum_{i=1}^S \left(\frac{n_i}{N}\right)^2
    \label{eq:simpson}\]</span> <span class="math inline">\(S\)</span> is the number of companies, and <span class="math inline">\(N\)</span> is the number of OSS authors within the project. For example, a measure of <span class="math inline">\(D=0.5\)</span> would suggest that there is a 50% chance that two randomly selected contributors are from different companies.</p>
<p>As a result of this data processing, several variables of interest have been defined for further analysis (<a href="#tbl-variables" class="quarto-xref">Table&nbsp;2</a>). As many of these variables represent counts and are heavily skewed, a simple <span class="math inline">\(\log\)</span> transformation was applied. The following section will describe the statistical models and methodologies used to test the previously stated hypotheses.</p>
<div id="tbl-variables" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: List of used variables, their roles, and applied transformations
</figcaption>
<div aria-describedby="tbl-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable Name</th>
<th style="text-align: left;">Definition</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Transformation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">Age of the OSS project in months</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;">Identity</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bookmarks</td>
<td style="text-align: left;">Number of uses who have bookmarked the project</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;"><span class="math inline">\(\log\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Issues</td>
<td style="text-align: left;">Number of active reported issues</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;"><span class="math inline">\(\log\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Size</td>
<td style="text-align: left;">Size of the code repository</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;"><span class="math inline">\(\log\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Commits</td>
<td style="text-align: left;">Number of code commits recorded</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;"><span class="math inline">\(\log\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fork</td>
<td style="text-align: left;">Number of code copies</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;"><span class="math inline">\(\log\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intensity</td>
<td style="text-align: left;">Code contribution intensity by dominant firm</td>
<td style="text-align: left;">Independent</td>
<td style="text-align: left;">Identity</td>
</tr>
<tr class="even">
<td style="text-align: left;">License</td>
<td style="text-align: left;">Used license (Public Domain, Permissive, Copyleft)</td>
<td style="text-align: left;">Independent</td>
<td style="text-align: left;">Factorization</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Centrality of main contributor</td>
<td style="text-align: left;">Degree centrality of the main contributor</td>
<td style="text-align: left;">Independent</td>
<td style="text-align: left;">Identity</td>
</tr>
<tr class="even">
<td style="text-align: left;">SDI</td>
<td style="text-align: left;">SDI value of the project</td>
<td style="text-align: left;">Dependent</td>
<td style="text-align: left;">Identity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Collaborator</td>
<td style="text-align: left;">Number of firms contributing to the project</td>
<td style="text-align: left;">Dependent</td>
<td style="text-align: left;">Identity</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<p>First, a Poisson regression will investigate the relationship between independent variables and the number of collaborators in an OSS project. Second, a Monte Carlo approach will test a potential U-shaped relationship between SDI and a project’s productivity.</p>
<section id="statistical-modeling" class="level3">
<h3 class="anchored" data-anchor-id="statistical-modeling">Statistical Modeling</h3>
<p>I used a Poisson regression model to analyze the relationship between independent variables and the number of firms contributing to an OSS project. A Poisson regression is an appropriate model for count data that are non-negative and has the form: <span class="math display">\[\log{\mu_i} = \beta_0 + \beta_1X_{1i} + \beta_2X_{2i} + \ldots
    \label{eq:poisson_reg}\]</span> in which <span class="math inline">\(\mu_i\)</span> is the expected value of the dependent variable, <span class="math inline">\(\beta_0\)</span> is the intercept, and <span class="math inline">\(\beta_1\)</span> to <span class="math inline">\(\beta_n\)</span> are the coefficients for the predictors.</p>
<p>I have fitted the Poisson regression model using maximum likelihood estimations via the <em>statsmodel</em> package in Python <span class="citation" data-cites="seabold2010statsmodels">(<a href="#ref-seabold2010statsmodels" role="doc-biblioref">Seabold and Perktold 2010</a>)</span>. The <span class="math inline">\(\beta\)</span>-coefficients were estimated along with their standard errors and p-values. Values were determined to have a statistically significant effect on the dependent variable at <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>Overall model fitness was assessed through model deviance and residual analysis. Model deviance is calculated as <span class="math inline">\(-2\)</span> times the log-likelihood of the fitted model parameters and compares how much likelihood the model has gained over the intercept-only model. In addition, as there might be potential endogeneity issues, I further computed the partial correlations between predictors and the error terms. A significant partial correlation provides evidence of endogeneity, even in the absence of instrumental variables. While this method cannot correct biased estimates, it can give a good indication of the presence of bias <span class="citation" data-cites="abdallah2015">(<a href="#ref-abdallah2015" role="doc-biblioref">Abdallah, Goergen, and O’Sullivan 2015</a>)</span>.</p>
</section>
<section id="u-shape-analysis" class="level3">
<h3 class="anchored" data-anchor-id="u-shape-analysis">U-Shape Analysis</h3>
<p>In many cases, researchers have not employed appropriate methodologies to detect U-shaped relationships, leading to the publication of inaccurate positive results <span class="citation" data-cites="haans2016">(<a href="#ref-haans2016" role="doc-biblioref">Haans, Pieters, and He 2016</a>)</span>. Specifically, past research has often only regressed the dependent variable <span class="math inline">\(Y\)</span> on the independent variable <span class="math inline">\(X\)</span> and its square <span class="math inline">\(X^2\)</span>: <span class="math display">\[Y = \beta_0 + \beta_1 X + \beta_2 X^2\]</span> A significant and positive <span class="math inline">\(\beta_2\)</span> would suggest a U-shaped relationship, while a negative coefficient implies an inverted U-shape relationship. One can further add additional control variables to this regression to account for potential confounders.</p>
<p>However, <span class="citation" data-cites="lind2010">Lind and Mehlum (<a href="#ref-lind2010" role="doc-biblioref">2010</a>)</span> showed that this process is not sufficient to demonstrate a U-shape relationship and proposed the following conditions: First, <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\beta_1\)</span> need the correct sign and be statistically significant. Second, the slope at both ends of the data range must be of sufficient steepness. In detail, at the high end of the data range <span class="math inline">\(X_H\)</span>, the slope, <span class="math inline">\(\beta_1 + 2\beta_2X_H\)</span>, needs to be significantly different from <span class="math inline">\(0\)</span> and positive, while at the low range, it is negative. Third and last, the turning point of the U-shape relationship, <span class="math inline">\(-\beta_1 / 2\beta_2\)</span>, needs to be within the data range. To test for these conditions, I employed a Monte-Carlo approach due to the complexity and nonstandard error assumptions of these requirements <span class="citation" data-cites="hastie2009">(<a href="#ref-hastie2009" role="doc-biblioref">Hastie, Tibshirani, and Friedman 2009</a>)</span>. This commonly used approach involves generating multiple datasets by random sampling with replacement from the dataset of interest. For each generated dataset, one can then compute the statistics of interest, converging to the true probability distribution of possible outcomes. This approach ensures a robust estimation of parameters and provides insight into the sensitivity and uncertainty of the estimates.</p>
<p>To ensure reliable parameters, I generated <span class="math inline">\(10,000\)</span> datasets by randomly sampling with replacement from my datasets and followed the steps outlined above to compute the relevant U-shape statistics as well as the corresponding 95% confidence intervals.</p>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="descriptive-findings" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-findings">Descriptive Findings</h2>
<p>A descriptive overview of all used variables is given in <a href="#tbl-descriptive_stats" class="quarto-xref">Table&nbsp;3</a> as more detailed information regarding distributions and correlations is provided in the appendix. As anticipated, most projects seem to have dominant contributors with a median commit intensity of 96.85 (interquartile range, IQR=82.78-99.39), an average of 87.65 (SD=17.90) and ranging from 17.89 to 99.99.</p>
<p>License choices show a more balanced distribution, with 60% of projects using permissive licenses, 9.1% using copyleft licenses, and an unexpected 31% of projects in the public domain. The low use of copyleft licenses by firms is unsurprising, given the restriction they include on developers and derivative works. However, the high amount of companies contributing to projects without clear licenses and, therefore, governance has not previously been discussed extensively.</p>
<p>Overall code contributions, issues, bookmarks, forks and size, and number of collaborators within projects demonstrate high variations (<a href="#tbl-descriptive_stats" class="quarto-xref">Table&nbsp;3</a>). This is unsurprising as most of these variables have long-tailed distributions with several highly productive and active projects (see Appendix). Interestingly, many projects investigated within this analysis are rather old, with an average of nearly <span class="math inline">\(60.57\)</span> months (<span class="math inline">\(SD = 35.13\)</span>). This is rather unexpected as OSS is commonly seen as a relatively new phenomenon, with many projects only being actively developed for a couple of years.</p>
<div id="tbl-descriptive_stats" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descriptive_stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Descriptive statistics
</figcaption>
<div aria-describedby="tbl-descriptive_stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: center;"><strong>N = 1,127</strong><sup>1</sup></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intensity</td>
<td style="text-align: center;">87.65 (17.90)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Issues</td>
<td style="text-align: center;">470.23 (1,247.49)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bookmarks</td>
<td style="text-align: center;">5,461.25 (15,132.53)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Forks</td>
<td style="text-align: center;">1,748.65 (5,128.34)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Size</td>
<td style="text-align: center;">441,016.27 (1,545,038.86)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: center;">60.57 (35.13)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Centrality</td>
<td style="text-align: center;">60.23 (21.66)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Collaborators</td>
<td style="text-align: center;">4.09 (4.53)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SDI</td>
<td style="text-align: center;">0.37 (0.24)</td>
</tr>
<tr class="even">
<td style="text-align: left;">License</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Copyleft</td>
<td style="text-align: center;">102 (9.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Permissive</td>
<td style="text-align: center;">675 (60%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Public Domain</td>
<td style="text-align: center;">350 (31%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Commits</td>
<td style="text-align: center;">1,346.49 (4,260.29)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Additionally, it is surprising to discover that, on average <span class="math inline">\(4.07\)</span> companies are actively working on OSS projects (<span class="math inline">\(SD=4.53\)</span>), indicating that despite most projects being dominated by a single firm, other companies remain interested in contributing. However, the distribution of the number of collaborators is highly right-side-tailed, with a few projects having considerably more collaborating firms than others.</p>
<p>Similar but less extreme distribution skewness can also be observed within bookmarks, and the number of code commits. This indicates that some projects within the dataset are highly popular and productive. Further, the average SDI value of <span class="math inline">\(0.37\)</span> (<span class="math inline">\(SD=0.24\)</span>) suggests that projects can attract considerable diversity in contributors but also shows that projects vary between each other to a substantial degree. A similar level of variation is also expressed in the network centrality of the leading contributing with an average of <span class="math inline">\(60\)</span> (<span class="math inline">\(SD=22\)</span>), ranging from <span class="math inline">\(0.5\)</span> to <span class="math inline">\(79\)</span>. Not surprisingly, well known technology companies are occupying central aspects of the overall open-source contributor network as shown in <a href="#tbl-network_centrality_top10" class="quarto-xref">Table&nbsp;4</a>.</p>
<div id="tbl-network_centrality_top10" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-network_centrality_top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Top 10 firms by network centrality. Network centrality is expressed as a percentage of the maximum possible number of edges a node can have.
</figcaption>
<div aria-describedby="tbl-network_centrality_top10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Centrality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Google</td>
<td style="text-align: right;">79.5</td>
</tr>
<tr class="even">
<td>Microsoft</td>
<td style="text-align: right;">76.5</td>
</tr>
<tr class="odd">
<td>Amazon</td>
<td style="text-align: right;">76.0</td>
</tr>
<tr class="even">
<td>Red Hat</td>
<td style="text-align: right;">74.0</td>
</tr>
<tr class="odd">
<td>IBM</td>
<td style="text-align: right;">71.0</td>
</tr>
<tr class="even">
<td>STMicroelectronics</td>
<td style="text-align: right;">70.5</td>
</tr>
<tr class="odd">
<td>VMware</td>
<td style="text-align: right;">67.5</td>
</tr>
<tr class="even">
<td>Intel</td>
<td style="text-align: right;">67.5</td>
</tr>
<tr class="odd">
<td>GitHub</td>
<td style="text-align: right;">67.0</td>
</tr>
<tr class="even">
<td>SAP</td>
<td style="text-align: right;">65.5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="inferential-results" class="level2">
<h2 class="anchored" data-anchor-id="inferential-results">Inferential Results</h2>
<p>I conducted a Poisson regression to examine the relationship between the independent variables and the number of collaborators in a project. This regression analysis was used to examine hypotheses 1, 2, 4, and 5 stated in the previous section. The U-shape relationship in hypothesis 3 was tested separately.</p>
<section id="poisson-regression-results" class="level3">
<h3 class="anchored" data-anchor-id="poisson-regression-results">Poisson Regression Results</h3>
<p>Overall the model was statistical significant (<span class="math inline">\(F(11, 1115)=247.58\)</span>, <span class="math inline">\(p&lt;0.001\)</span>) with a Pseudo R-square of <span class="math inline">\(0.86\)</span>. The overview of the estimated parameters is presented in <a href="#tbl-regression_results" class="quarto-xref">Table&nbsp;5</a>.</p>
<p><strong>Hypothesis 1:</strong> <em>OSS projects in which a single firm dominates will have fewer collaborating partners</em></p>
<p>The results indicate that commit intensity is a significant and robust predictor of the number of project collaborators (<span class="math inline">\(\beta = -0.025, z=-11.93, p&lt;0.001\)</span>). Thus, for each percentage point increase in commit intensity by the dominating firm, the expected number of collaborators will be reduced by 2.5% holding all other predictors constant. To estimate the overall importance of this predictor on the model, the change in Pseudo R-square was measured when intensity was added to the regression model in a separate step. This showed an increase in <span class="math inline">\(R^2\)</span> of <span class="math inline">\(0.27\)</span>, considerably improving the model without this predictor (<span class="math inline">\(R^2=0.56\)</span>). This demonstrates that while the predictor is significant to the model, other predictors also contribute to explaining the total number of collaborators per project. In summary, projects dominated by single cooperations have a significantly lower total number of corporate contributors.</p>
<p><strong>Hypothesis 2:</strong> <em>OSS projects with more restrictive licenses have fewer collaborators.</em></p>
<p>Within this regression results, copyleft and permissive licenses were compared against projects in the public domain. The results suggest that permissive licenses significantly lower the number of collaborators compared to projects without licenses (<span class="math inline">\(\beta = -0.186, z=-5.30, p&lt;0.001\)</span>). This would suggest that projects with a permissive license have 16.7% fewer expected collaborators than those in the public domain. In contrast, copyleft licenses do not significantly affect the number of collaborators compared to those without licenses (<span class="math inline">\(\beta = -0.105, z=-1.69, p=0.092\)</span>). However, the total number of projects with copyleft licenses is with 102 relatively smaller than compared to the other groups, indicating a lack of statistical power. In summary, there is some evidence that projects with more restrictive licenses have fewer overall collaborating firms.</p>
<p><strong>Hypothesis 4</strong> <em>OSS projects which have high network-value contributors will attract more collaborators</em></p>
<p>The regression results suggest that network centrality is not a significant predictor for the total number of collaborators in OSS projects (<span class="math inline">\(\beta =-0.002, z=-1.16, p=0.241\)</span>) independent of other predictors. Further, while the estimated effect size is small compared to other predictors, the direction of the effect is in contrast to the stated hypothesis. In summary, OSS projects with high network-value contributors do not affect the number of collaborators.</p>
<p><strong>Hypothesis 5</strong> <em>Projects dominated by a firm with a high number of contributors will attract more collaborators than a dominating company with few contributors.</em></p>
<p>To test to which extent the network centrality of a dominating firm is predictive of the number of collaborators in a project, I have tested the interaction effect between intensity and network centrality ( <a href="#fig-interaction_effect" class="quarto-xref">Figure&nbsp;4</a>). The estimated interaction coefficient suggests that projects in which firms with high network centrality dominate do not have a significantly higher number of collaborators (<span class="math inline">\(\beta = 0.0005, z=1.53, p=0.122\)</span>). The small effect size of both centrality and its interaction with intensity would suggest that these variables are of little importance in predicting the number of project collaborators independently. In summary, OSS projects dominated by a single company with high network value are not significantly affecting the degree of collaboration.</p>
<div id="fig-interaction_effect" class="lightbox quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-interaction_effect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/interaction_centrality_intensity.png" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3"><img src="images/interaction_centrality_intensity.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interaction_effect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Interaction effect between centrality and intensity on the number of project collaborators.
</figcaption>
</figure>
</div>
<section id="other-predictors" class="level4">
<h4 class="anchored" data-anchor-id="other-predictors">Other Predictors</h4>
<p>Several other control variables were also useful in predicting the number of collaborators. Specifically, size (<span class="math inline">\(\beta = 0.08, z = 8.32, p&lt;0.0001\)</span>), commits (<span class="math inline">\(\beta = 0.081, z = 6.27, p&lt;0.0001\)</span>), forks (<span class="math inline">\(\beta = 0.101, z = 5.32, p&lt;0.0001\)</span>), and age (<span class="math inline">\(\beta = -0.0016, z = -3.11, p&lt;0.002\)</span>) contributed significantly to the explained variance. Interestingly, bookmarks (<span class="math inline">\(\beta = 0.018, z = 1.121, p&lt;0.262\)</span>) were not significantly associated with the number of collaborators, presumably due to multicollinearity between the number of bookmarks and forks. These predictors are expressed on a logarithmic scale, so the coefficients represent the proportional change in the expected count of project collaborators on that scale.</p>
<div id="tbl-regression_results" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression_results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Poisson regression results on the number of project collaborators. Both Copyleft and Permissive compare effects against projects within the public domain.
</figcaption>
<div aria-describedby="tbl-regression_results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: center;"><strong>IRR</strong><sup>1</sup></th>
<th style="text-align: center;"><strong>SE</strong><sup>1</sup></th>
<th style="text-align: center;"><strong>Statistic</strong></th>
<th style="text-align: center;"><strong>95% CI</strong><sup>1</sup></th>
<th style="text-align: center;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">log(Bookmarks)</td>
<td style="text-align: center;">1.02</td>
<td style="text-align: center;">0.017</td>
<td style="text-align: center;">1.12</td>
<td style="text-align: center;">0.99, 1.05</td>
<td style="text-align: center;">0.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Forks)</td>
<td style="text-align: center;">1.11</td>
<td style="text-align: center;">0.019</td>
<td style="text-align: center;">5.42</td>
<td style="text-align: center;">1.07, 1.15</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log(Issues)</td>
<td style="text-align: center;">0.95</td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">-5.24</td>
<td style="text-align: center;">0.93, 0.97</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Size)</td>
<td style="text-align: center;">1.08</td>
<td style="text-align: center;">0.009</td>
<td style="text-align: center;">8.32</td>
<td style="text-align: center;">1.06, 1.10</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log(Commits)</td>
<td style="text-align: center;">1.09</td>
<td style="text-align: center;">0.013</td>
<td style="text-align: center;">6.27</td>
<td style="text-align: center;">1.06, 1.11</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">-3.12</td>
<td style="text-align: center;">1.00, 1.00</td>
<td style="text-align: center;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intensity</td>
<td style="text-align: center;">0.97</td>
<td style="text-align: center;">0.002</td>
<td style="text-align: center;">-11.9</td>
<td style="text-align: center;">0.97, 0.98</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">License</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Public Domain</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Copyleft</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.062</td>
<td style="text-align: center;">-1.69</td>
<td style="text-align: center;">0.80, 1.02</td>
<td style="text-align: center;">0.092</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Permissive</td>
<td style="text-align: center;">0.83</td>
<td style="text-align: center;">0.035</td>
<td style="text-align: center;">-5.30</td>
<td style="text-align: center;">0.78, 0.89</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Centrality</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.003</td>
<td style="text-align: center;">-1.17</td>
<td style="text-align: center;">0.99, 1.00</td>
<td style="text-align: center;">0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intensity * Centrality</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.000</td>
<td style="text-align: center;">1.55</td>
<td style="text-align: center;">1.00, 1.00</td>
<td style="text-align: center;">0.12</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="u-shape-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="u-shape-analysis-1">U-Shape Analysis</h3>
<p>Hypothesis 5 proposed a U-Shape relationship between collaboration heterogeneity and project productivity. This relationship was tested through the Monte-Carlo methods outlined in method section, and the empirical relationship is presented in <a href="#fig-u_shape" class="quarto-xref">Figure&nbsp;5</a>. Regression results suggest a statistical significance model (<span class="math inline">\(F(6, 1120)=82.71\)</span>, <span class="math inline">\(p&lt;0.0001\)</span>) with an R-square of <span class="math inline">\(0.307\)</span>. The overview of the estimated parameters is presented in <a href="#tbl-regression_results_u_shape" class="quarto-xref">Table&nbsp;6</a>. Both SDI (<span class="math inline">\(\beta = -4.369, t(6)=-8.709, p&lt;0.001\)</span>) and its squared value (<span class="math inline">\(\beta = 3.588, t(6)=6.259, p&lt;0.001\)</span>) demonstrated to be significant predictor of code commits. These results indicate a U-Shape relationship between productivity, measured as code commits, and collaboration heterogeneity. The performed Monte-Carlo simulations further supported these findings by estimating the left-most slope at -4.326 (95% CI [-5.357, -3.285]) and right-most slope at 2.393 (95% CI [1.037, 3.738]). The more considerable variance in the right-most slope estimations may represent the lack of data points from highly heterogeneous projects. Nevertheless, estimated confidence intervals point to a robust parameter estimation different from zero. Further, the turning point of the U-Shape was estimated to be at 0.615 SDI ([95% CI 0.547, 0.723]), suggesting a rather mid-point-centered relationship between these two variables. These findings imply a robust U-Shape relationship between productivity and collaboration heterogeneity.</p>
<div id="fig-u_shape" class="lightbox quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-u_shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/u_shape.png" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="quarto-lightbox-gallery-4"><img src="images/u_shape.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-u_shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Relationship between code commits and SDI. The red line indicates the estimated U-shape relationship between commits and SDI.
</figcaption>
</figure>
</div>
<div id="tbl-regression_results_u_shape" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression_results_u_shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Least square regression results on the logarithmic number of project commits. The unstandardized coefficients and standard errors are reported.
</figcaption>
<div aria-describedby="tbl-regression_results_u_shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: center;"><strong>Beta</strong></th>
<th style="text-align: center;"><strong>SE</strong><sup>1</sup></th>
<th style="text-align: center;"><strong>Statistic</strong></th>
<th style="text-align: center;"><strong>95% CI</strong><sup>1</sup></th>
<th style="text-align: center;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SDI</td>
<td style="text-align: center;">-4.4</td>
<td style="text-align: center;">0.502</td>
<td style="text-align: center;">-8.71</td>
<td style="text-align: center;">-5.4, -3.4</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(SDI^2\)</span></td>
<td style="text-align: center;">3.6</td>
<td style="text-align: center;">0.573</td>
<td style="text-align: center;">6.26</td>
<td style="text-align: center;">2.5, 4.7</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log(Bookmarks)</td>
<td style="text-align: center;">0.09</td>
<td style="text-align: center;">0.034</td>
<td style="text-align: center;">2.79</td>
<td style="text-align: center;">0.03, 0.16</td>
<td style="text-align: center;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Forks)</td>
<td style="text-align: center;">-0.04</td>
<td style="text-align: center;">0.037</td>
<td style="text-align: center;">-1.16</td>
<td style="text-align: center;">-0.12, 0.03</td>
<td style="text-align: center;">0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log(Issues)</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">0.024</td>
<td style="text-align: center;">2.38</td>
<td style="text-align: center;">0.01, 0.10</td>
<td style="text-align: center;">0.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(Size)</td>
<td style="text-align: center;">0.22</td>
<td style="text-align: center;">0.018</td>
<td style="text-align: center;">12.4</td>
<td style="text-align: center;">0.18, 0.25</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The statistical analysis indicates that single-firm dominance and license restrictions can influence the degree of project collaborations among firms in OSS projects. Contributor centrality alone appears to have an estimated negative impact on the number of collaborations, although the effect is insignificant. Further, the degree of collaboration heterogeneity has a U-shape influence on project productivity. In summary, the findings support hypotheses related to single-firm dominance, license restrictiveness, and the effect of collaboration heterogeneity on productivity but contradict those centered on firms’ network centrality.</p>
<section id="implications" class="level2">
<h2 class="anchored" data-anchor-id="implications">Implications</h2>
<section id="firm-commit-intensity" class="level3">
<h3 class="anchored" data-anchor-id="firm-commit-intensity">Firm Commit Intensity</h3>
<p>In line with previous research, commit intensity has a strong negative correlation with the number of project collaborators <span class="citation" data-cites="zhang2022 schaarschmidt2015 hawkins2004 oneil2022">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-schaarschmidt2015" role="doc-biblioref">Schaarschmidt, Walsh, and von Kortzfleisch 2015</a>; <a href="#ref-hawkins2004" role="doc-biblioref">Hawkins 2004</a>; <a href="#ref-oneil2022" role="doc-biblioref">O’Neil et al. 2022</a>)</span>. This should not come as a surprise, as the more a project is dominated by a single firm, the less room for collaboration exists for others. Further, projects with high intensity potentially deter others from contributing as they might be concerned about providing free labor to the dominant company <span class="citation" data-cites="zhou2017 zhang2018 zhou2012">(<a href="#ref-zhou2017" role="doc-biblioref">M. Zhou et al. 2017</a>; <a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>; <a href="#ref-zhou2012" role="doc-biblioref">M. Zhou and Mockus 2012</a>)</span>. Another aspect that could potentially influence this effect is the degree of modularization within the project. Projects with less internal interdependencies might offer more room for others to contribute independently of the main code committer. This would enable collaborators to work on different aspects of the OSS, which may be commercially independent of the main code base. For example, <span class="citation" data-cites="zhou2017">M. Zhou et al. (<a href="#ref-zhou2017" role="doc-biblioref">2017</a>)</span> found in their analyses of the Linux Kernel, a particular large OSS project, a considerable degree of modularization. The authors showed that code contributors would typically restrict themselves only to specific modules, such as hardware drivers, which were of commercial importance to their employer only but not to others. Thus, larger OSS projects might allow commercial organizations to contribute to OSS without directly collaborating with competitors. This calls into question the extent to which firms are working together on OSS projects.</p>
<p>From a theoretical view, these findings are broadly in line with the perspective of TCE as firms potentially aim to exert control over projects through domination of the code base itself while utilizing the open distribution channels of OSS <span class="citation" data-cites="zhang2022 schaarschmidt2015">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-schaarschmidt2015" role="doc-biblioref">Schaarschmidt, Walsh, and von Kortzfleisch 2015</a>)</span>. This increases asset specificity as most new software features are oriented towards the strategic goal of the dominating firm and increase the cost of others to run or adopt the software for other purposes <span class="citation" data-cites="williamson1985">(<a href="#ref-williamson1985" role="doc-biblioref">Williamson 1985</a>)</span>. Similarly, more modular code bases with an existing amount of heterogeneous contributors allow companies to collaborate on non-differentiating features and highly specific modules of the code base <span class="citation" data-cites="zhou2017">(<a href="#ref-zhou2017" role="doc-biblioref">M. Zhou et al. 2017</a>)</span>.</p>
<p>The large number of projects with significant commit intensity also implies that companies might not be interested in generating collaborative relationships. Thus, firms might be less interested in lowering their fixed costs or generating valuable collaborative relationships with other firms but potentially aim to sell complementary products or increase their brand image with independent developers. This strategy can be utilized to establish or enter new markets by providing OSS as a free product or service for customers <span class="citation" data-cites="anderson2008">(<a href="#ref-anderson2008" role="doc-biblioref">Anderson and Gatignon 2008</a>)</span>. However, <span class="citation" data-cites="alexy2018">Alexy et al. (<a href="#ref-alexy2018" role="doc-biblioref">2018</a>)</span> showed that this strategy will only result in sustainable competitive advantage when both fixed costs are lowered and complementary products are sold with the OSS. Firms would need to attract a substantial amount of independent open-source developers or open their projects to other firms to enable the reduction of developer costs and therefore sustain their advantage over time.</p>
</section>
<section id="sssec:licenses" class="level3">
<h3 class="anchored" data-anchor-id="sssec:licenses">Licenses</h3>
<p>The findings regarding the effects of different licenses on OSS collaborations align broadly with prior research <span class="citation" data-cites="medappa2020 zhou2022 aksulu2010">(<a href="#ref-medappa2020" role="doc-biblioref">Medappa and Srivastava 2020</a>; <a href="#ref-zhou2022" role="doc-biblioref">Z. Z. Zhou and Choudhary 2022</a>; <a href="#ref-aksulu2010" role="doc-biblioref">Aksulu and Wade 2010</a>)</span> and are consistent with what TCE theory would predict <span class="citation" data-cites="williamson1985">(<a href="#ref-williamson1985" role="doc-biblioref">Williamson 1985</a>)</span>. Firms that have chosen more restrictive licenses are imposing higher transaction costs on potential corporate contributors and their ability to modify and adapt the OSS solution. It is interesting that despite the flexibility and low restrictions offered by ‘permissive’ licenses, projects in the public domain without any formal license seem to be preferred. Firms might be motivated to choose ‘permissive’ licenses to increase the project specificity and the cost of competitors to integrate the software into their products as the license requires attribution of the original authors on all derivative works <span class="citation" data-cites="rosen2004">(<a href="#ref-rosen2004" role="doc-biblioref">Rosen 2004</a>)</span>. This form of hierarchical controls aligns well with the TCE theory, but questions remain as to the degree to which these licenses are enforceable in practice. Legal enforcement of open-source licenses is rare, and disputes are often only resolved through community discussions or voluntary efforts by the licensee <span class="citation" data-cites="gomulkiewicz2011 vonwelser2018">(<a href="#ref-gomulkiewicz2011" role="doc-biblioref">Gomulkiewicz 2011</a>; <a href="#ref-vonwelser2018" role="doc-biblioref">von Welser 2018</a>)</span>. Thus, hierarchical control over OSS projects through licensing agreements might be less effective than control via code contributions and project governance.</p>
<p>Further, <span class="citation" data-cites="singh2012">Singh and Phelps (<a href="#ref-singh2012" role="doc-biblioref">2012</a>)</span> found that project managers are more likely to choose a license that is consistent with the expectations of the users and that of similar projects, pointing to a more social than a strategic component of the decision-making progress. In addition, not all previous studies agree with these findings. For example, <span class="citation" data-cites="colazo2009">Colazo and Fang (<a href="#ref-colazo2009" role="doc-biblioref">2009</a>)</span> showed in their analysis of 244 OSS projects that the use of ‘copyleft’ licenses increased the total amount of participating authors within a project. However, the study was based on older data, and the number of corporate OSS contributors has significantly increased in the last ten years, leading to more ‘permissive’ forms of licenses and potentially explaining the discrepancy between the two studies <span class="citation" data-cites="medappa2020">(<a href="#ref-medappa2020" role="doc-biblioref">Medappa and Srivastava 2020</a>)</span>. Nevertheless, the presented empirical findings suggest that the choice of open-source license plays a significant part in the degree of collaboration.</p>
</section>
<section id="sssec:network_centrality" class="level3">
<h3 class="anchored" data-anchor-id="sssec:network_centrality">Network Centrality</h3>
<p>The here presented empirical results were unable to demonstrate that the network centrality of the largest contributor has a significant effect on the total number of collaborators in an open-source project. Previous work has shown that network value is correlated with revenue <span class="citation" data-cites="liu2022">(<a href="#ref-liu2022" role="doc-biblioref">Liu, Lai, and He 2022</a>)</span>, and RBV theory has suggested that firms might be interested in collaborating with high-value network firms, thus emphasizing the importance of network centrality for a firm’s financial and strategic success. In detail, low-value firms might aim to seek technical and relational spillover from a high-value company through an active collaboration <span class="citation" data-cites="williamson1975 williamson1985">(<a href="#ref-williamson1975" role="doc-biblioref">Williamson 1975</a>, <a href="#ref-williamson1985" role="doc-biblioref">1985</a>)</span>. The empirical findings here could not support this view, and high-network value firms with high levels of code contributions could not attract collaborators independently of other factors. Interestingly, the direction of the estimated effect, although of small magnitude, points to a decrease in the expected number of collaborators and contradicts the previously formulated hypothesis.</p>
<p>However, the lack of collaboration does not exclude technical spillover effects in OSS. Firms might ‘free ride’ on existing OSS projects independently on the importance of the main contributing firm <span class="citation" data-cites="kumar2011">(<a href="#ref-kumar2011" role="doc-biblioref">Kumar, Gordon, and Srinivasan 2011</a>)</span>. Specifically, many firms are utilizing smaller open-source projects, which are maintained by only a few independent developers, to support crucial infrastructure or network security <span class="citation" data-cites="silic2016">(<a href="#ref-silic2016" role="doc-biblioref">Silic and Back 2016</a>)</span>. These firms rely on community contributors or other organizations to fix software bugs or security issues within these OSS. This contradicts previous predictions, which assumed that firms would aim to control resources necessary for their business and avoid dependencies <span class="citation" data-cites="pfeffer1978 williamson1985">(<a href="#ref-pfeffer1978" role="doc-biblioref">Pfeffer and Salancik 1978</a>; <a href="#ref-williamson1985" role="doc-biblioref">Williamson 1985</a>)</span>. While these risks might be manageable in circumstances in which the OSS maintainer is a trusted and reliable party, the presented results suggest that this may not lead to a pooled R&amp;D among parties.</p>
</section>
<section id="productivity" class="level3">
<h3 class="anchored" data-anchor-id="productivity">Productivity</h3>
<p>The presented results have supported the theoretical predictions by TCE that both firms with low and high levels of contribution heterogeneity will show increased productivity. This is in inline with previous research showing that diversity and distribution of code contributors are significantly associated with productivity in OSS projects <span class="citation" data-cites="izquierdo2019 vasilescu2015 lerner2002 tan2007">(<a href="#ref-izquierdo2019" role="doc-biblioref">Izquierdo et al. 2019</a>; <a href="#ref-vasilescu2015" role="doc-biblioref">Vasilescu et al. 2015</a>; <a href="#ref-lerner2002" role="doc-biblioref">Lerner and Tirole 2002</a>; <a href="#ref-tan2007" role="doc-biblioref">Tan, Mookerjee, and Singh 2007</a>)</span>. <span class="citation" data-cites="zhang2020a">Zhang et al. (<a href="#ref-zhang2020a" role="doc-biblioref">2020</a>)</span> also found similar results and showed that a firm’s degree of collaboration is a significant predictor of productivity. However, this study is the first to show a U-shaped relationship between heterogeneity of collaboration and productivity, suggesting a more complex relationship between code author diversity and productivity. Specifically, low-heterogeneous projects are potentially better able to control and direct development efforts, while high-heterogeneous projects can use a significantly larger development community. Projects in the middle of these two extremes potentially suffer from an increase in governance cost without a significantly enlarged group of developers, leading to a decrease in productivity <span class="citation" data-cites="capra2008">(<a href="#ref-capra2008" role="doc-biblioref">Capra, Francalanci, and Merlo 2008</a>)</span>.</p>
<p>However, the causal direction between governance structure, heterogeneous collaborations, and productivity is unclear. <span class="citation" data-cites="zajac1993">Zajac and Olsen (<a href="#ref-zajac1993" role="doc-biblioref">1993</a>)</span>, in line with TCE, suggested that firms will choose governance structures depending on the total value of transactions. Thus, firms may lower transaction costs by selecting less hierarchical controls in the hope of increasing the number of external developers for software maintenance and ultimately leading to productivity gains <span class="citation" data-cites="demil2006">(<a href="#ref-demil2006" role="doc-biblioref">Demil and Lecocq 2006</a>)</span>. The alternative view is that the choice of governance is more reactive to the number of external contributors. As more firms and independent developers contribute to a project, the more the initiating firm needs to invest in governance to coordinate the project direction. Thus, integrating existing collaborators into the governance process can lower the hierarchical control of the initiating firm but enables it to share the cost of governance with others <span class="citation" data-cites="zhang2020a">(<a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>)</span>. For example, Google has spun out Kubernetes, a server orchestration framework, as an open source to enter the cloud computing market. Over time the projects attracted a considerable number of collaborations, and the firm decided to transfer the IP into an independent foundation to effectively share control and cost of governance <span class="citation" data-cites="honeypot2022">(<a href="#ref-honeypot2022" role="doc-biblioref">Honeypot 2022</a>)</span>. In summary, while the presented results here cannot address the direction of the causal relationship, they nevertheless show a more complex relationship between productivity and collaboration.</p>
</section>
</section>
<section id="limitations-and-future-research" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-research">Limitations and Future Research</h2>
<p>As with all studies, this analysis has some limitations which should be acknowledged. First and foremost, the used data provides only a snapshot of the complete software development journey in 2022 and cannot reflect activities not recorded within GitHub’s commits. This study has also explicitly excluded activities by independent developers, which may have contributed to the degree of collaboration among firms and the overall productivity of projects. However, the proportion of corporate OSS contributors has been rising steadily, and many projects are exclusively driven by developers employed by companies <span class="citation" data-cites="stephens2021">(<a href="#ref-stephens2021" role="doc-biblioref">Stephens 2021</a>)</span>.</p>
<p>One can further challenge the use of commits to measure project productivity and the size of the organizational contribution to OSS <span class="citation" data-cites="zhang2020a">(<a href="#ref-zhang2020a" role="doc-biblioref">Zhang et al. 2020</a>)</span>. Indeed, while this measurement form is expected in the literature <span class="citation" data-cites="zhang2022 zhang2018 shaikh2019 oneil2022 teixeira2016">(<a href="#ref-zhang2022" role="doc-biblioref">Zhang, He, and Zhou 2022</a>; <a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>; <a href="#ref-shaikh2019" role="doc-biblioref">Shaikh and Levina 2019</a>; <a href="#ref-oneil2022" role="doc-biblioref">O’Neil et al. 2022</a>; <a href="#ref-teixeira2016" role="doc-biblioref">Teixeira, Mian, and Hytti 2016</a>)</span>, the content of commits and the related effort required can vary greatly. For example, a commit can contain a simple change to rectify a typographic error or add new software features consisting of hundreds of lines of code. Nevertheless, commits are an established metric to measure code productivity, but future research might consider investigating its validity.</p>
<p>In addition to the limitations above, the study does not reveal the causal direction of detected effects. For instance, the causal relationship between commit intensity and the number of collaborators is uncertain. To gain a more comprehensive understanding of potential causal relationships, future research should consider implementing a longitudinal study design or utilizing instrumental variables. These methods can provide more detailed insights into the relationships between variables over time and help control for potential confounding factors that may affect the observed correlations. In addition, qualitative studies can complement these quantitative findings by providing contextual information and an in-depth understanding of how both commit intensity and licenses impact corporate OSS collaboration.</p>
</section>
<section id="managerial-implications" class="level2">
<h2 class="anchored" data-anchor-id="managerial-implications">Managerial Implications</h2>
<p>A critical problem for many OSS strategies is publicly integrating internal and external innovations while reducing fixed costs through collaboration. These strategies often aim to challenge an entrenched incumbent or set standards within a new market. However, this approach will often fail should the firm be unable to attract collaborators and reduce their fixed costs <span class="citation" data-cites="alexy2018">(<a href="#ref-alexy2018" role="doc-biblioref">Alexy et al. 2018</a>)</span>. Hence, firms should be conscious to not only open-source their software but actively provide opportunities for others to contribute. This can include simplifying the OSS license or structuring the code modularly to enable independent development by others. Additionally, firms need to recognize that while dominating OSS projects may provide control over the project, it can also decrease the project’s appeal as a collaboration opportunity for others. Firms can potentially enhance the openness of their OSS projects and signal their willingness to collaborate with other potential partners by forming strategic partnerships for co-development. These partnerships may go beyond communities of independent developers and should include other cooperations to signal a commitment to openness and collaboration. Further, firms should also consider the higher coordination cost and potentially reduced productivity which can be associated with an increase in collaborative partners. Companies might consider mitigating these factors by sharing governance costs with collaborators early and providing a governance structure to support the growth in contributors.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The here presented results are one of the few analyses of OSS which aim to investigate the practicalities of open-source development within cooperations. Most past research has mainly focused on why firms are contributing to OSS <span class="citation" data-cites="vanhaverbeke2006 dahlander2010 vrande2010 bogers2011">(<a href="#ref-vanhaverbeke2006" role="doc-biblioref">Vanhaverbeke 2006</a>; <a href="#ref-dahlander2010" role="doc-biblioref">Dahlander and Gann 2010</a>; <a href="#ref-vrande2010" role="doc-biblioref">Vrande, Vanhaverbeke, and Gassmann 2010</a>; <a href="#ref-bogers2011" role="doc-biblioref">Bogers 2011</a>)</span> and little has been done to provide practitioners with insights on how to implement and foster OSS projects. Especially in the IT sector, the use and contribution to OSS projects is a standard practice <span class="citation" data-cites="blackduck2016">(<a href="#ref-blackduck2016" role="doc-biblioref">Black Duck 2016</a>)</span>, and many startups have utilized OSS as a starting point to enter a new market <span class="citation" data-cites="taherizadeh2019">(<a href="#ref-taherizadeh2019" role="doc-biblioref">Taherizadeh and Isabelle 2019</a>)</span>. However, project-level decisions, such as the choice of OSS license, are sometimes not made in alignment with the firm’s strategic objectives but to conform with social norms and expectations <span class="citation" data-cites="singh2012">(<a href="#ref-singh2012" role="doc-biblioref">Singh and Phelps 2012</a>)</span>. This is not surprising given the more social-political perspective in which OSS originated <span class="citation" data-cites="perens1999">(<a href="#ref-perens1999" role="doc-biblioref">Perens 1999</a>)</span> and which remain essential for creating a valuable and thriving open-source community around a particular project <span class="citation" data-cites="shaikh2019">(<a href="#ref-shaikh2019" role="doc-biblioref">Shaikh and Levina 2019</a>)</span>. However, as many recent OSS projects are initiated and dominated by corporate entities, it is important to align project-level decisions with the firm’s overall strategic goals. Thus, more research on evidence-based practices to effectively implement OSS strategies and grow associated projects are needed to guide both OSS developer and managers.</p>
<p>This analysis has aimed to address some of these more practical aspects of OSS development by providing empirical evidence for practitioners seeking to attract corporate collaboration. Specifically, my analysis has shown that commit intensity and the choice of license influence the degree of collaboration among firms in OSS projects. Further, this investigation also demonstrated a more complex relationship between collaboration heterogeneity and productivity, a potentially important consideration for practitioners. Overall, the study highlights the importance of firms actively providing opportunities for others to contribute to their OSS projects and recognizing the potential trade-offs between control and collaboration.</p>
<p>Future studies should continue to explore the complex causal relationships between collaboration, governance, and productivity in the context of OSS projects. Enabling firms to open source their internal software, collaborate with others, and utilize existing OSS projects effectively and in alignment with their overall strategic objectives.</p>
</section>

</section>

<div id="quarto-appendix" class="default"><section id="appendix" class="level2 appendix"><h2 class="anchored quarto-appendix-heading">Appendix</h2><div class="quarto-appendix-contents">

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/distributions.png" class="img-fluid figure-img"></p>
<figcaption>Distribution of variables. Histograms of continuous and bar plot of categorized variables.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/heatmap.png" class="img-fluid figure-img"></p>
<figcaption>Correlation Heatmap. Correlations between continuous variables</figcaption>
</figure>
</div>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Figure&nbsp;1: Number of open-source repositories on the popular OSS collaboration platform GitHub between 2012 and 2022</span>
<span class="glightbox-desc lightbox-desc-2">Figure&nbsp;2: Structural approach to software development. Modified based on <span class="citation" data-cites="west2006">West and Gallagher (<a href="#ref-west2006" role="doc-biblioref">2006</a>)</span></span>
<span class="glightbox-desc lightbox-desc-3">Figure&nbsp;4: Interaction effect between centrality and intensity on the number of project collaborators.</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;5: Relationship between code commits and SDI. The red line indicates the estimated U-shape relationship between commits and SDI.</span>
</div>

</div></section><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-abdallah2015" class="csl-entry" role="listitem">
Abdallah, Wissam, Marc Goergen, and Noel O’Sullivan. 2015. <span>“Endogeneity: <span>How Failure</span> to <span>Correct</span> for It Can <span>Cause Wrong Inferences</span> and <span>Some Remedies</span>.”</span> <em>British Journal of Management</em> 26 (4): 791–804. <a href="https://doi.org/10.1111/1467-8551.12113">https://doi.org/10.1111/1467-8551.12113</a>.
</div>
<div id="ref-abdelkafi2013" class="csl-entry" role="listitem">
Abdelkafi, Nizar, Sergiy Makhotin, and Thorsten Posselt. 2013. <span>“Business Model Innovations for Electric Mobility What Can Be Learned from Existing Business Model Patterns?”</span> <em>International Journal of Innovation Management</em> 17 (01): 1340003. <a href="https://doi.org/10.1142/S1363919613400033">https://doi.org/10.1142/S1363919613400033</a>.
</div>
<div id="ref-ahmad2021" class="csl-entry" role="listitem">
Ahmad, Rizwan. 2021. <span>“A <span>Critical Review</span> of <span>Open Source Software Development</span>: <span>Freedom</span> or <span>Benefit Libertarian View Versus Corporate View</span>.”</span> <em>IT Professional</em> 23 (1): 16–26. <a href="https://doi.org/10.1109/MITP.2020.3014450">https://doi.org/10.1109/MITP.2020.3014450</a>.
</div>
<div id="ref-aksulu2010" class="csl-entry" role="listitem">
Aksulu, Altay, and Michael Wade. 2010. <span>“A <span>Comprehensive Review</span> and <span>Synthesis</span> of <span>Open Source Research</span>.”</span> <em>Journal of the Association for Information Systems</em> 11 (11). <a href="https://doi.org/10.17705/1jais.00245">https://doi.org/10.17705/1jais.00245</a>.
</div>
<div id="ref-alexy2018" class="csl-entry" role="listitem">
Alexy, Oliver, Joel West, Helge Klapper, and Markus Reitzig. 2018. <span>“Surrendering Control to Gain Advantage: <span>Reconciling</span> Openness and the Resource-Based View of the Firm.”</span> <em>Strategic Management Journal</em> 39 (6): 1704–27. <a href="https://doi.org/10.1002/smj.2706">https://doi.org/10.1002/smj.2706</a>.
</div>
<div id="ref-anderson2008" class="csl-entry" role="listitem">
Anderson, Erin, and Hubert Gatignon. 2008. <span>“Firms and the <span>Creation</span> of <span>New Markets</span>.”</span> In <em>Handbook of <span>New Institutional Economics</span></em>, edited by Claude Ménard and Mary M. Shirley, 401–31. <span>Berlin, Heidelberg</span>: <span>Springer</span>. <a href="https://doi.org/10.1007/978-3-540-69305-5_17">https://doi.org/10.1007/978-3-540-69305-5_17</a>.
</div>
<div id="ref-barney1991a" class="csl-entry" role="listitem">
Barney, Jay. 1991. <span>“Firm <span>Resources</span> and <span>Sustained Competitive Advantage</span>.”</span> <em>Journal of Management</em> 17 (1): 99–120. <a href="https://doi.org/10.1177/014920639101700108">https://doi.org/10.1177/014920639101700108</a>.
</div>
<div id="ref-benkler2002" class="csl-entry" role="listitem">
Benkler, Yochai. 2002. <span>“Coase’s <span>Penguin</span>, or, <span>Linux</span> and "<span>The Nature</span> of the <span>Firm</span>".”</span> <em>The Yale Law Journal</em> 112 (3): 369–446. <a href="https://doi.org/10.2307/1562247">https://doi.org/10.2307/1562247</a>.
</div>
<div id="ref-blackduck2016" class="csl-entry" role="listitem">
Black Duck. 2016. <span>“Future of <span>Open Source Survey Results</span>.”</span> <a href="https://www.slideshare.net/blackducksoftware/2016-future-of-open-source-survey-results">https://www.slideshare.net/blackducksoftware/2016-future-of-open-source-survey-results</a>.
</div>
<div id="ref-blind2023" class="csl-entry" role="listitem">
Blind, Knut, and Torben Schubert. 2023. <span>“Estimating the <span>GDP</span> Effect of <span>Open Source</span>&nbsp; <span>Software</span> and Its Complementarities with <span>R</span>&amp;<span>D</span> and Patents: Evidence and Policy Implications.”</span> <em>The Journal of Technology Transfer</em>, February. <a href="https://doi.org/10.1007/s10961-023-09993-x">https://doi.org/10.1007/s10961-023-09993-x</a>.
</div>
<div id="ref-bogers2011" class="csl-entry" role="listitem">
Bogers, Marcel. 2011. <span>“The Open Innovation Paradox: Knowledge Sharing and Protection in <span>R</span>&amp;<span>D</span> Collaborations.”</span> <em>European Journal of Innovation Management</em> 14 (1): 93–117. <a href="https://doi.org/10.1108/14601061111104715">https://doi.org/10.1108/14601061111104715</a>.
</div>
<div id="ref-bogers2017" class="csl-entry" role="listitem">
Bogers, Marcel, Ann-Kristin Zobel, Allan Afuah, Esteve Almirall, Sabine Brunswicker, Linus Dahlander, Lars Frederiksen, et al. 2017. <span>“The Open Innovation Research Landscape: Established Perspectives and Emerging Themes Across Different Levels of Analysis.”</span> <em>Industry and Innovation</em> 24 (1): 8–40. <a href="https://doi.org/10.1080/13662716.2016.1240068">https://doi.org/10.1080/13662716.2016.1240068</a>.
</div>
<div id="ref-bonaccorsi2007" class="csl-entry" role="listitem">
Bonaccorsi, Andrea, Dario Lorenzi, Monica Merito, and Cristina Rossi. 2007. <span>“Business <span>Firms</span>’ <span>Engagement</span> in <span>Community Projects</span>. <span>Empirical Evidence</span> and <span>Further Developments</span> of the <span>Research</span>.”</span> In <em>First <span>International Workshop</span> on <span>Emerging Trends</span> in <span>FLOSS Research</span> and <span>Development</span> (<span>FLOSS</span>’07: <span>ICSE Workshops</span> 2007)</em>, 13–13. <a href="https://doi.org/10.1109/FLOSS.2007.3">https://doi.org/10.1109/FLOSS.2007.3</a>.
</div>
<div id="ref-butler2021" class="csl-entry" role="listitem">
Butler, Simon, Jonas Gamalielsson, Björn Lundell, Christoffer Brax, Johan Sjöberg, Anders Mattsson, Tomas Gustavsson, Jonas Feist, and Erik Lönroth. 2021. <span>“On <span>Company Contributions</span> to <span>Community Open Source Software Projects</span>.”</span> <em>IEEE Transactions on Software Engineering</em> 47 (7): 1381–401. <a href="https://doi.org/10.1109/TSE.2019.2919305">https://doi.org/10.1109/TSE.2019.2919305</a>.
</div>
<div id="ref-capra2008" class="csl-entry" role="listitem">
Capra, Eugenio, Chiara Francalanci, and Francesco Merlo. 2008. <span>“An <span>Empirical Study</span> on the <span>Relationship Between Software Design Quality</span>, <span>Development Effort</span> and <span>Governance</span> in <span>Open Source Projects</span>.”</span> <em>IEEE Transactions on Software Engineering</em> 34 (6): 765–82. <a href="https://doi.org/10.1109/TSE.2008.68">https://doi.org/10.1109/TSE.2008.68</a>.
</div>
<div id="ref-casalo2009" class="csl-entry" role="listitem">
Casaló, Luis V., Jesús Cisneros, Carlos Flavián, and Miguel Guinalíu. 2009. <span>“Determinants of Success in Open Source Software Networks.”</span> <em>Industrial Management &amp; Data Systems</em> 109 (4): 532–49. <a href="https://doi.org/10.1108/02635570910948650">https://doi.org/10.1108/02635570910948650</a>.
</div>
<div id="ref-chesbrough2014" class="csl-entry" role="listitem">
Chesbrough, Henry, and Marcel Bogers. 2014. <span>“Explicating <span>Open Innovation</span>: <span>Clarifying</span> an <span>Emerging Paradigm</span> for <span>Understanding Innovation</span>.”</span> {{SSRN Scholarly Paper}}. <span>Rochester, NY</span>. <a href="https://papers.ssrn.com/abstract=2427233">https://papers.ssrn.com/abstract=2427233</a>.
</div>
<div id="ref-chesbrough2006" class="csl-entry" role="listitem">
Chesbrough, Henry, and Adrienne Kardon Crowther. 2006. <span>“Beyond High Tech: Early Adopters of Open Innovation in Other Industries.”</span> <em>R&amp;D Management</em> 36 (3): 229–36. <a href="https://doi.org/10.1111/j.1467-9310.2006.00428.x">https://doi.org/10.1111/j.1467-9310.2006.00428.x</a>.
</div>
<div id="ref-cheung2004" class="csl-entry" role="listitem">
Cheung, Kui-yin, and Ping Lin. 2004. <span>“Spillover Effects of <span>FDI</span> on Innovation in <span>China</span>: <span>Evidence</span> from the Provincial Data.”</span> <em>China Economic Review</em> 15 (1): 25–44. <a href="https://doi.org/10.1016/S1043-951X(03)00027-0">https://doi.org/10.1016/S1043-951X(03)00027-0</a>.
</div>
<div id="ref-colazo2009" class="csl-entry" role="listitem">
Colazo, Jorge, and Yulin Fang. 2009. <span>“Impact of License Choice on <span>Open Source Software</span> Development Activity.”</span> <em>Journal of the American Society for Information Science and Technology</em> 60 (5): 997–1011. <a href="https://doi.org/10.1002/asi.21039">https://doi.org/10.1002/asi.21039</a>.
</div>
<div id="ref-dahlander2010" class="csl-entry" role="listitem">
Dahlander, Linus, and David M. Gann. 2010. <span>“How Open Is Innovation?”</span> <em>Research Policy</em> 39 (6): 699–709. <a href="https://doi.org/10.1016/j.respol.2010.01.013">https://doi.org/10.1016/j.respol.2010.01.013</a>.
</div>
<div id="ref-degroote2020" class="csl-entry" role="listitem">
De Groote, Julia K., and Julia Backmann. 2020. <span>“Initiating <span>Open Innovation Collaborations Between Incumbents</span> and <span>Startups</span>: <span>How Can David</span> and <span>Goliath Get Along</span>?”</span> <em>International Journal of Innovation Management</em> 24 (2): 2050011. <a href="https://doi.org/10.1142/S1363919620500115">https://doi.org/10.1142/S1363919620500115</a>.
</div>
<div id="ref-demontalvo2004" class="csl-entry" role="listitem">
de Montalvo, Uta Wehn, Els van de Kar, and Carleen Maitland. 2004. <span>“Resource-Based Interdependencies in Value Networks for Mobile Internet Services.”</span> In <em>Proceedings of the 6th International Conference on <span>Electronic</span> Commerce - <span>ICEC</span> ’04</em>, 627. <span>Delft, The Netherlands</span>: <span>ACM Press</span>. <a href="https://doi.org/10.1145/1052220.1052300">https://doi.org/10.1145/1052220.1052300</a>.
</div>
<div id="ref-debianfoundation2023" class="csl-entry" role="listitem">
Debian Foundation. 2023. <span>“Debian <span>Free Software Guidelines</span>.”</span> <em>Wikipedia</em>, January. <a href="https://wiki.debian.org/DebianFreeSoftwareGuidelines">https://wiki.debian.org/DebianFreeSoftwareGuidelines</a>.
</div>
<div id="ref-demil2006" class="csl-entry" role="listitem">
Demil, Benoît, and Xavier Lecocq. 2006. <span>“Neither <span>Market</span> nor <span>Hierarchy</span> nor <span>Network</span>: <span>The Emergence</span> of <span>Bazaar Governance</span>.”</span> <em>Organization Studies</em> 27 (10): 1447–66. <a href="https://doi.org/10.1177/0170840606067250">https://doi.org/10.1177/0170840606067250</a>.
</div>
<div id="ref-deshpande2008" class="csl-entry" role="listitem">
Deshpande, Amit, and Dirk Riehle. 2008. <span>“The <span>Total Growth</span> of <span>Open Source</span>.”</span> In <em>Open <span>Source Development</span>, <span>Communities</span> and <span>Quality</span></em>, edited by Barbara Russo, Ernesto Damiani, Scott Hissam, Björn Lundell, and Giancarlo Succi, 275:197–209. <span>Boston, MA</span>: <span>Springer US</span>. <a href="https://doi.org/10.1007/978-0-387-09684-1_16">https://doi.org/10.1007/978-0-387-09684-1_16</a>.
</div>
<div id="ref-dibona1999" class="csl-entry" role="listitem">
DiBona, Chris, Sam Ockman, and Mark Stone, eds. 1999. <em>Open <span>Sources</span>: <span>Voices</span> from the <span>Open Source Revolution</span></em>. 1st edition. <span>Beijing ; Sebastopol, CA</span>: <span>O’Reilly Media</span>.
</div>
<div id="ref-dyer1997" class="csl-entry" role="listitem">
Dyer, Jeffrey H. 1997. <span>“Effective Interim Collaboration: How Firms Minimize Transaction Costs and Maximise Transaction Value.”</span> <em>Strategic Management Journal</em> 18 (7): 535–56. <a href="https://doi.org/10.1002/(SICI)1097-0266(199708)18:7<535::AID-SMJ885>3.0.CO;2-Z">https://doi.org/10.1002/(SICI)1097-0266(199708)18:7&lt;535::AID-SMJ885&gt;3.0.CO;2-Z</a>.
</div>
<div id="ref-dyer1998" class="csl-entry" role="listitem">
Dyer, Jeffrey H., and Harbir Singh. 1998. <span>“The <span>Relational View</span>: <span>Cooperative Strategy</span> and <span>Sources</span> of <span>Interorganizational Competitive Advantage</span>.”</span> <em>The Academy of Management Review</em> 23 (4): 660–79. <a href="https://doi.org/10.2307/259056">https://doi.org/10.2307/259056</a>.
</div>
<div id="ref-epamsystems2023" class="csl-entry" role="listitem">
EPAM Systems. 2023. <span>“Open <span>Source Contributor Index</span> (<span>OSCI</span>).”</span> EPAM Systems. <a href="https://github.com/epam/OSCI">https://github.com/epam/OSCI</a>.
</div>
<div id="ref-erlenhov2019" class="csl-entry" role="listitem">
Erlenhov, Linda, Francisco Gomes de Oliveira Neto, Riccardo Scandariato, and Philipp Leitner. 2019. <span>“Current and <span>Future Bots</span> in <span>Software Development</span>.”</span> In <em>2019 <span>IEEE</span>/<span>ACM</span> 1st <span>International Workshop</span> on <span>Bots</span> in <span>Software Engineering</span> (<span>BotSE</span>)</em>, 7–11. <a href="https://doi.org/10.1109/BotSE.2019.00009">https://doi.org/10.1109/BotSE.2019.00009</a>.
</div>
<div id="ref-fjeldstad2012" class="csl-entry" role="listitem">
Fjeldstad, Øystein D., Charles C. Snow, Raymond E. Miles, and Christopher Lettl. 2012. <span>“The Architecture of Collaboration.”</span> <em>Strategic Management Journal</em> 33 (6): 734–50. <a href="https://doi.org/10.1002/smj.1968">https://doi.org/10.1002/smj.1968</a>.
</div>
<div id="ref-gassmann2004" class="csl-entry" role="listitem">
Gassmann, Oliver, and Ellen Enkel. 2004. <span>“Towards a <span>Theory</span> of <span>Open Innovation</span>: <span>Three Core Process Archetypes</span>.”</span> <em>University of St.Gallen</em> 6 (January).
</div>
<div id="ref-germonprez2013" class="csl-entry" role="listitem">
Germonprez, Matt, Jonathan Allen, Brian Warner, Jamie Hill, and Glenn McClements. 2013. <span>“Open Source Communities of Competitors.”</span> <em>Interactions</em> 20 (November): 54–59. <a href="https://doi.org/10.1145/2527191">https://doi.org/10.1145/2527191</a>.
</div>
<div id="ref-ghapanchi2014" class="csl-entry" role="listitem">
Ghapanchi, Amir Hossein, Claes Wohlin, and Aybüke Aurum. 2014. <span>“Resources Contributing to Gaining Competitive Advantage for Open Source Software Projects: <span>An</span> Application of Resource-Based Theory.”</span> <em>International Journal of Project Management</em> 32 (1): 139–52. <a href="https://doi.org/10.1016/j.ijproman.2013.03.002">https://doi.org/10.1016/j.ijproman.2013.03.002</a>.
</div>
<div id="ref-githubinc.2023" class="csl-entry" role="listitem">
GitHub Inc. 2023. <span>“<span>GitHub</span>.com.”</span> <em>GitHub</em>. <a href="https://github.com">https://github.com</a>.
</div>
<div id="ref-gomulkiewicz2011" class="csl-entry" role="listitem">
Gomulkiewicz, Robert W. 2011. <span>“Enforcement of <span>Open Source Software Licenses</span>: <span>The MDY Trio</span>’s <span>Inconvenient Complications</span>.”</span> <em>Yale Journal of Law and Technology</em> 14: 106.
</div>
<div id="ref-grant1991" class="csl-entry" role="listitem">
Grant, Robert M. 1991. <span>“The <span>Resource-Based Theory</span> of <span>Competitive Advantage</span>: <span>Implications</span> for <span>Strategy Formulation</span>.”</span> <em>California Management Review</em> 33 (3): 114–35. <a href="https://doi.org/10.2307/41166664">https://doi.org/10.2307/41166664</a>.
</div>
<div id="ref-greene2018" class="csl-entry" role="listitem">
Greene, Jay. 2018. <span>“Microsoft <span>Is Buying GitHub</span> for $7.5 <span>Billion</span> in <span>Stock</span>.”</span> <em>Wall Street Journal</em>, June. <a href="https://www.wsj.com/articles/microsoft-to-acquire-github-for-7-5-billion-in-stock-1528118504">https://www.wsj.com/articles/microsoft-to-acquire-github-for-7-5-billion-in-stock-1528118504</a>.
</div>
<div id="ref-gulati1998" class="csl-entry" role="listitem">
Gulati, Ranjay, and Harbir Singh. 1998. <span>“The <span>Architecture</span> of <span>Cooperation</span>: <span>Managing Coordination Costs</span> and <span>Appropriation Concerns</span> in <span>Strategic Alliances</span>.”</span> <em>Administrative Science Quarterly</em> 43 (4): 781–814. <a href="https://doi.org/10.2307/2393616">https://doi.org/10.2307/2393616</a>.
</div>
<div id="ref-haans2016" class="csl-entry" role="listitem">
Haans, Richard F. J., Constant Pieters, and Zi-Lin He. 2016. <span>“Thinking about <span>U</span>: <span>Theorizing</span> and Testing <span>U-</span> and Inverted <span class="nocase">U-shaped</span> Relationships in Strategy Research.”</span> <em>Strategic Management Journal</em> 37 (7): 1177–95. <a href="https://doi.org/10.1002/smj.2399">https://doi.org/10.1002/smj.2399</a>.
</div>
<div id="ref-hastie2009" class="csl-entry" role="listitem">
Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2009. <em>The <span>Elements</span> of <span>Statistical Learning</span></em>. Springer <span>Series</span> in <span>Statistics</span>. <span>New York, NY</span>: <span>Springer</span>. <a href="https://doi.org/10.1007/978-0-387-84858-7">https://doi.org/10.1007/978-0-387-84858-7</a>.
</div>
<div id="ref-hawkins2004" class="csl-entry" role="listitem">
Hawkins, Richard E. 2004. <span>“The Economics of Open Source Software for a Competitive Firm.”</span> <em>NETNOMICS: Economic Research and Electronic Networking</em> 6 (2): 103–17. <a href="https://doi.org/10.1007/s11066-004-2717-z">https://doi.org/10.1007/s11066-004-2717-z</a>.
</div>
<div id="ref-helfat2003" class="csl-entry" role="listitem">
Helfat, Constance E., and Margaret A. Peteraf. 2003. <span>“The Dynamic Resource-Based View: Capability Lifecycles.”</span> <em>Strategic Management Journal</em> 24 (10): 997–1010. <a href="https://doi.org/10.1002/smj.332">https://doi.org/10.1002/smj.332</a>.
</div>
<div id="ref-honeypot2022" class="csl-entry" role="listitem">
Honeypot. 2022. <span>“Kubernetes: <span>The Documentary</span> [<span>PART</span> 1].”</span> <a href="https://www.youtube.com/watch?v=BE77h7dmoQU">https://www.youtube.com/watch?v=BE77h7dmoQU</a>.
</div>
<div id="ref-hsieh2016" class="csl-entry" role="listitem">
Hsieh, Ching-Tang, Hao-Chen Huang, and Wei-Long Lee. 2016. <span>“Using Transaction Cost Economics to Explain Open Innovation in Start-Ups.”</span> <em>Management Decision</em> 54 (9): 2133–56. <a href="https://doi.org/10.1108/MD-01-2016-0012">https://doi.org/10.1108/MD-01-2016-0012</a>.
</div>
<div id="ref-izquierdo2019" class="csl-entry" role="listitem">
Izquierdo, Daniel, Nicole Huesman, Alexander Serebrenik, and Gregorio Robles. 2019. <span>“<span>OpenStack Gender Diversity Report</span>.”</span> <em>IEEE Software</em> 36 (1): 28–33. <a href="https://doi.org/10.1109/MS.2018.2874322">https://doi.org/10.1109/MS.2018.2874322</a>.
</div>
<div id="ref-krishnamurthy2005" class="csl-entry" role="listitem">
Krishnamurthy, Sandeep. 2005. <span>“A <span>Managerial Overview</span> of <span>Open Source Software</span>.”</span> {{SSRN Scholarly Paper}}. <span>Rochester, NY</span>. <a href="https://papers.ssrn.com/abstract=649903">https://papers.ssrn.com/abstract=649903</a>.
</div>
<div id="ref-kumar2011" class="csl-entry" role="listitem">
Kumar, Vineet, Brett R. Gordon, and Kannan Srinivasan. 2011. <span>“Competitive <span>Strategy</span> for <span>Open Source Software</span>.”</span> <em>Marketing Science</em> 30 (6): 1066–78. <a href="https://doi.org/10.1287/mksc.1110.0669">https://doi.org/10.1287/mksc.1110.0669</a>.
</div>
<div id="ref-langlois1989" class="csl-entry" role="listitem">
Langlois, Richard N., and Paul L. Robertson. 1989. <span>“Explaining <span>Vertical Integration</span>: <span>Lessons</span> from the <span>American Automobile Industry</span>.”</span> <em>The Journal of Economic History</em> 49 (2): 361–75. <a href="https://doi.org/10.1017/S0022050700007993">https://doi.org/10.1017/S0022050700007993</a>.
</div>
<div id="ref-lerner2002" class="csl-entry" role="listitem">
Lerner, Josh, and Jean Tirole. 2002. <span>“Some <span>Simple Economics</span> of <span>Open Source</span>.”</span> <em>The Journal of Industrial Economics</em> 50 (2): 197–234. <a href="https://doi.org/10.1111/1467-6451.00174">https://doi.org/10.1111/1467-6451.00174</a>.
</div>
<div id="ref-lin2008" class="csl-entry" role="listitem">
Lin, Lihui. 2008. <span>“Impact of User Skills and Network Effects on the Competition Between Open Source and Proprietary Software.”</span> <em>Electronic Commerce Research and Applications</em>, Market transformation in a networked global economy, 7 (1): 68–81. <a href="https://doi.org/10.1016/j.elerap.2007.01.003">https://doi.org/10.1016/j.elerap.2007.01.003</a>.
</div>
<div id="ref-lind2010" class="csl-entry" role="listitem">
Lind, Jo Thori, and Halvor Mehlum. 2010. <span>“With or <span>Without U</span>? <span>The Appropriate Test</span> for a <span>U-Shaped Relationship</span>*.”</span> <em>Oxford Bulletin of Economics and Statistics</em> 72 (1): 109–18. <a href="https://doi.org/10.1111/j.1468-0084.2009.00569.x">https://doi.org/10.1111/j.1468-0084.2009.00569.x</a>.
</div>
<div id="ref-liu2022" class="csl-entry" role="listitem">
Liu, Fuzhen, Kee-hung Lai, and Chaocheng He. 2022. <span>“Open <span>Innovation</span> and <span>Market Value</span>: <span>An Extended Resource-Based View</span>.”</span> <em>IEEE Transactions on Engineering Management</em>, 1–14. <a href="https://doi.org/10.1109/TEM.2022.3166676">https://doi.org/10.1109/TEM.2022.3166676</a>.
</div>
<div id="ref-medappa2020" class="csl-entry" role="listitem">
Medappa, Poonacha K., and Shirish C. Srivastava. 2020. <span>“Ideological Shifts in Open Source Orchestration: Examining the Influence of Licence Choice and Organisational Participation on Open Source Project Outcomes.”</span> <em>European Journal of Information Systems</em> 29 (5): 500–520. <a href="https://doi.org/10.1080/0960085X.2020.1756003">https://doi.org/10.1080/0960085X.2020.1756003</a>.
</div>
<div id="ref-nagle2019" class="csl-entry" role="listitem">
Nagle, Frank. 2019. <span>“Open <span>Source Software</span> and <span>Firm Productivity</span>.”</span> <em>Management Science</em> 65 (3): 1191–1215. <a href="https://doi.org/10.1287/mnsc.2017.2977">https://doi.org/10.1287/mnsc.2017.2977</a>.
</div>
<div id="ref-newman2010" class="csl-entry" role="listitem">
Newman, M. E. J. 2010. <em>Networks: An Introduction</em>. <span>Oxford ; New York</span>: <span>Oxford University Press</span>.
</div>
<div id="ref-oneil2022" class="csl-entry" role="listitem">
O’Neil, Mathieu, Laure Muselli, Xiaolan Cai, and Stefano Zacchiroli. 2022. <span>“Co-Producing Industrial Public Goods on <span>GitHub</span>: <span>Selective</span> Firm Cooperation, Volunteer-Employee Labour and Participation Inequality.”</span> <em>New Media &amp; Society</em>, April, 14614448221090474. <a href="https://doi.org/10.1177/14614448221090474">https://doi.org/10.1177/14614448221090474</a>.
</div>
<div id="ref-octolab_gharchive" class="csl-entry" role="listitem">
OctoLab. 2021. <span>“<span>GHArchive</span>: <span>A</span> Structured Archive of <span>GitHub</span> Activity.”</span> <a href="https://www.gharchive.org/">https://www.gharchive.org/</a>.
</div>
<div id="ref-oxley1997" class="csl-entry" role="listitem">
Oxley, Joanne E. 1997. <span>“Appropriability <span>Hazards</span> and <span>Governance</span> in <span>Strategic Alliances</span>: <span>A Transaction Cost Approach</span>.”</span> <em>The Journal of Law, Economics, and Organization</em> 13 (2): 387–409. <a href="https://doi.org/10.1093/oxfordjournals.jleo.a023389">https://doi.org/10.1093/oxfordjournals.jleo.a023389</a>.
</div>
<div id="ref-perens1999" class="csl-entry" role="listitem">
Perens, Bruce. 1999. <span>“The <span>Open Source Definition</span>.”</span> In <em>Open <span>Sources</span>: <span>Voices</span> from the <span>Open Source Revolution</span></em>, edited by Chris DiBona, Sam Ockman, and Mark Stone, 1st edition. <span>Beijing ; Sebastopol, CA</span>: <span>O’Reilly Media</span>.
</div>
<div id="ref-pfeffer1978" class="csl-entry" role="listitem">
Pfeffer, Jeffrey, and Gerald R. Salancik. 1978. <span>“The <span>External Control</span> of <span>Organizations</span>: <span>A Resource Dependence Perspective</span>.”</span> {{SSRN Scholarly Paper}}. <span>Rochester, NY</span>. <a href="https://papers.ssrn.com/abstract=1496213">https://papers.ssrn.com/abstract=1496213</a>.
</div>
<div id="ref-prahalad2004" class="csl-entry" role="listitem">
Prahalad, C. K., and Venkat Ramaswamy. 2004. <span>“Co-Creation Experiences: <span>The</span> Next Practice in Value Creation.”</span> <em>Journal of Interactive Marketing</em> 18 (3): 5–14. <a href="https://doi.org/10.1002/dir.20015">https://doi.org/10.1002/dir.20015</a>.
</div>
<div id="ref-remneland-wikhamn2012" class="csl-entry" role="listitem">
Remneland-Wikhamn, Björn, and David Knights. 2012. <span>“Transaction <span>Cost Economics</span> and <span>Open Innovation</span>: <span>Implications</span> for <span>Theory</span> and <span>Practice</span>.”</span> <em>Creativity and Innovation Management</em> 21 (3): 277–89. <a href="https://doi.org/10.1111/j.1467-8691.2012.00639.x">https://doi.org/10.1111/j.1467-8691.2012.00639.x</a>.
</div>
<div id="ref-rosen2004" class="csl-entry" role="listitem">
Rosen, Lawrence. 2004. <em>Open <span>Source Licensing</span>: <span>Software Freedom</span> and <span>Intellectual Property Law</span></em>. Paperback edition. <span>Upper Saddle River, NJ</span>: <span>Prentice Hall</span>.
</div>
<div id="ref-sawhney2005" class="csl-entry" role="listitem">
Sawhney, Mohanbir, Gianmario Verona, and Emanuela Prandelli. 2005. <span>“Collaborating to Create: <span>The Internet</span> as a Platform for Customer Engagement in Product Innovation.”</span> <em>Journal of Interactive Marketing</em> 19 (4): 4–17. <a href="https://doi.org/10.1002/dir.20046">https://doi.org/10.1002/dir.20046</a>.
</div>
<div id="ref-schaarschmidt2015" class="csl-entry" role="listitem">
Schaarschmidt, Mario, Gianfranco Walsh, and Harald F. O. von Kortzfleisch. 2015. <span>“How Do Firms Influence Open Source Software Communities? <span>A</span> Framework and Empirical Analysis of Different Governance Modes.”</span> <em>Information and Organization</em> 25 (2): 99–114. <a href="https://doi.org/10.1016/j.infoandorg.2015.03.001">https://doi.org/10.1016/j.infoandorg.2015.03.001</a>.
</div>
<div id="ref-scott2003" class="csl-entry" role="listitem">
Scott, Brendan. 2003. <span>“Why Free Software Long Run <span>TCO</span> Must Be Lower.”</span> In <em><span>AUUGN</span></em>. <span>AUUG, Inc.</span>
</div>
<div id="ref-seabold2010statsmodels" class="csl-entry" role="listitem">
Seabold, Skipper, and Josef Perktold. 2010. <span>“Statsmodels: <span>Econometric</span> and Statistical Modeling with Python.”</span> In <em>9th Python in Science Conference</em>.
</div>
<div id="ref-sen2008b" class="csl-entry" role="listitem">
Sen, Ravi, Chandrasekar Subramaniam, and Matthew L. Nelson. 2008. <span>“Determinants of the <span>Choice</span> of <span>Open Source Software License</span>.”</span> <em>Journal of Management Information Systems</em> 25 (3): 207–40. <a href="https://doi.org/10.2753/MIS0742-1222250306">https://doi.org/10.2753/MIS0742-1222250306</a>.
</div>
<div id="ref-shaikh2019" class="csl-entry" role="listitem">
Shaikh, Maha, and Natalia Levina. 2019. <span>“Selecting an Open Innovation Community as an Alliance Partner: <span>Looking</span> for Healthy Communities and Ecosystems.”</span> <em>Research Policy</em>, The <span>Digital Transformation</span> of <span>Innovation</span> and <span>Entrepreneurship</span>, 48 (8): 103766. <a href="https://doi.org/10.1016/j.respol.2019.03.011">https://doi.org/10.1016/j.respol.2019.03.011</a>.
</div>
<div id="ref-silic2016" class="csl-entry" role="listitem">
Silic, Mario, and Andrea Back. 2016. <span>“The <span>Influence</span> of <span>Risk Factors</span> in <span>Decision-Making Process</span> for <span>Open Source Software Adoption</span>.”</span> <em>International Journal of Information Technology &amp; Decision Making</em> 15 (01): 151–85. <a href="https://doi.org/10.1142/S0219622015500364">https://doi.org/10.1142/S0219622015500364</a>.
</div>
<div id="ref-simpson1949" class="csl-entry" role="listitem">
Simpson, E. H. 1949. <span>“Measurement of <span>Diversity</span>.”</span> <em>Nature</em> 163 (4148): 688–88. <a href="https://doi.org/10.1038/163688a0">https://doi.org/10.1038/163688a0</a>.
</div>
<div id="ref-singh2012" class="csl-entry" role="listitem">
Singh, Param Vir, and Corey C. Phelps. 2012. <span>“Networks, <span>Social Influence</span> and the <span>Choice Among Competing Innovations</span>: <span>Insights</span> from <span>Open Source Software Licenses</span>.”</span> {{SSRN Scholarly Paper}}. <span>Rochester, NY</span>. <a href="https://doi.org/10.2139/ssrn.1436153">https://doi.org/10.2139/ssrn.1436153</a>.
</div>
<div id="ref-singh2011" class="csl-entry" role="listitem">
Singh, Param Vir, Yong Tan, and Vijay Mookerjee. 2011. <span>“Network <span>Effects</span>: <span>The Influence</span> of <span>Structural Capital</span> on <span>Open Source Project Success</span>.”</span> <em>Mis Quarterly</em> 35 (4): 813–29. <a href="https://www.jstor.org/stable/41409962">https://www.jstor.org/stable/41409962</a>.
</div>
<div id="ref-spdx2023" class="csl-entry" role="listitem">
SPDX. 2023. <span>“Software <span>Package Data Exchange</span> (<span>SPDX</span>).”</span> <a href="https://spdx.org/licenses/">https://spdx.org/licenses/</a>.
</div>
<div id="ref-stephens2021" class="csl-entry" role="listitem">
Stephens, Patrick. 2021. <span>“<span>OSCI</span> - <span>An</span> Analysis of Activities.”</span> <em>Open Source Index</em>. <a href="https://opensourceindex.io/p/data-deep-dive-2016-2020">https://opensourceindex.io/p/data-deep-dive-2016-2020</a>.
</div>
<div id="ref-taherizadeh2019" class="csl-entry" role="listitem">
Taherizadeh, Amir, and Diane Isabelle. 2019. <span>“Do Theories of Strategic Alliances Explain Open-Source Technological Collaborations?”</span> April.
</div>
<div id="ref-tan2007" class="csl-entry" role="listitem">
Tan, Yong, Vijay Mookerjee, and Param Singh. 2007. <span>“Social <span>Capital</span>, <span>Structural Holes</span> and <span>Team Composition</span>: <span>Collaborative Networks</span> of the <span>Open Source Software Community</span>.”</span> <em>ICIS 2007 Proceedings</em>, December. <a href="https://aisel.aisnet.org/icis2007/155">https://aisel.aisnet.org/icis2007/155</a>.
</div>
<div id="ref-teixeira2016" class="csl-entry" role="listitem">
Teixeira, Jose, Salman Mian, and Ulla Hytti. 2016. <span>“Cooperation Among Competitors in the Open-Source Arena: <span>The</span> Case of <span>OpenStack</span>.”</span> <span>arXiv</span>. <a href="https://doi.org/10.48550/arXiv.1612.09462">https://doi.org/10.48550/arXiv.1612.09462</a>.
</div>
<div id="ref-linux" class="csl-entry" role="listitem">
Torvalds, Linus. 1991. <span>“Linux.”</span> Self-published. <a href="https://github.com/torvalds/linux/tree/v0.01">https://github.com/torvalds/linux/tree/v0.01</a>.
</div>
<div id="ref-tripsas2000" class="csl-entry" role="listitem">
Tripsas, Mary, and Giovanni Gavetti. 2000. <span>“Capabilities, Cognition, and Inertia: Evidence from Digital Imaging.”</span> <em>Strategic Management Journal</em> 21 (10-11): 1147–61. <a href="https://doi.org/10.1002/1097-0266(200010/11)21:10/11<1147::AID-SMJ128>3.0.CO;2-R">https://doi.org/10.1002/1097-0266(200010/11)21:10/11&lt;1147::AID-SMJ128&gt;3.0.CO;2-R</a>.
</div>
<div id="ref-vanhaverbeke2006" class="csl-entry" role="listitem">
Vanhaverbeke, Wim. 2006. <span>“The Inter-Organizational Context of Open Innovation.”</span> <em>Open Innovation: Researching a New Paradigm</em>, January.
</div>
<div id="ref-vanhaverbeke2014" class="csl-entry" role="listitem">
Vanhaverbeke, Wim, and Myriam Cloodt. 2014. <span>“Theories of the <span>Firm</span> and <span>Open Innovation</span>.”</span> In <em>New <span>Frontiers</span> in <span>Open Innovation</span></em>, edited by Henry Chesbrough, Wim Vanhaverbeke, and Joel West, 0. <span>Oxford University Press</span>. <a href="https://doi.org/10.1093/acprof:oso/9780199682461.003.0014">https://doi.org/10.1093/acprof:oso/9780199682461.003.0014</a>.
</div>
<div id="ref-vanhaverbeke2008" class="csl-entry" role="listitem">
Vanhaverbeke, Wim, Vareska Vrande, and Henry Chesbrough. 2008. <span>“Understanding the <span>Advantages</span> of <span>Open Innovation Practices</span> in <span>Corporate Venturing</span> in <span>Terms</span> of <span>Real Options</span>.”</span> <em>Creativity and Innovation Management</em> 17 (December): 251–58. <a href="https://doi.org/10.1111/j.1467-8691.2008.00499.x">https://doi.org/10.1111/j.1467-8691.2008.00499.x</a>.
</div>
<div id="ref-vasilescu2015" class="csl-entry" role="listitem">
Vasilescu, Bogdan, Daryl Posnett, Baishakhi Ray, Mark G. J. van den Brand, Alexander Serebrenik, Premkumar Devanbu, and Vladimir Filkov. 2015. <span>“Gender and <span>Tenure Diversity</span> in <span>GitHub Teams</span>.”</span> In <em>Proceedings of the 33rd <span>Annual ACM Conference</span> on <span>Human Factors</span> in <span>Computing Systems</span></em>, 3789–98. <span>CHI</span> ’15. <span>New York, NY, USA</span>: <span>Association for Computing Machinery</span>. <a href="https://doi.org/10.1145/2702123.2702549">https://doi.org/10.1145/2702123.2702549</a>.
</div>
<div id="ref-vonhippel2007" class="csl-entry" role="listitem">
Von Hippel, Eric. 2007. <span>“Horizontal Innovation Networksby and for Users.”</span> <em>Industrial and Corporate Change</em> 16 (2): 293–315. <a href="https://doi.org/10.1093/icc/dtm005">https://doi.org/10.1093/icc/dtm005</a>.
</div>
<div id="ref-vonwelser2018" class="csl-entry" role="listitem">
von Welser, Marcus. 2018. <span>“Opposing the <span>Monetization</span> of <span>Linux</span>: <span>McHardy</span> v. <span>Geniatech</span> &amp; <span>Addressing Copyright</span> <span>‘<span>Trolling</span>’</span> in <span>Germany</span>.”</span> <em>International Free and Open Source Software Law - Review</em> 10 (1): 9–20. <a href="https://doi.org/10.5033/ifosslr.v10i1.128">https://doi.org/10.5033/ifosslr.v10i1.128</a>.
</div>
<div id="ref-vrande2010" class="csl-entry" role="listitem">
Vrande, Vareska, Wim Vanhaverbeke, and Oliver Gassmann. 2010. <span>“Broadening the Scope of Open Innovation: <span>Past</span> Research, Current State and Future Directions.”</span> <em>International Journal of Technology Management</em> 52 (October): 221–35. <a href="https://doi.org/10.1504/IJTM.2010.035974">https://doi.org/10.1504/IJTM.2010.035974</a>.
</div>
<div id="ref-wang2005b" class="csl-entry" role="listitem">
Wang, Tongsen, Lei Wu, and Zhangxi Lin. 2005. <span>“The Revival of <span>Mozilla</span> in the Browser War Against <span>Internet Explorer</span>.”</span> In <em>Proceedings of the 7th International Conference on <span>Electronic</span> Commerce</em>, 159–66. <span>ICEC</span> ’05. <span>New York, NY, USA</span>: <span>Association for Computing Machinery</span>. <a href="https://doi.org/10.1145/1089551.1089583">https://doi.org/10.1145/1089551.1089583</a>.
</div>
<div id="ref-west2006" class="csl-entry" role="listitem">
West, Joel, and Scott Gallagher. 2006. <span>“Challenges of Open Innovation: The Paradox of Firm Investment in Open-Source Software.”</span> <em>R&amp;D Management</em> 36 (3): 319–31. <a href="https://doi.org/10.1111/j.1467-9310.2006.00436.x">https://doi.org/10.1111/j.1467-9310.2006.00436.x</a>.
</div>
<div id="ref-west2008" class="csl-entry" role="listitem">
West, Joel, and Karim Lakhani. 2008. <span>“Getting <span>Clear About Communities</span> in <span>Open Innovation</span>.”</span> <em>Industry and Innovation</em> 15 (2): 223–31.
</div>
<div id="ref-west2014" class="csl-entry" role="listitem">
West, Joel, Ammon Salter, Wim Vanhaverbeke, and Henry Chesbrough. 2014. <span>“Open Innovation: <span>The</span> Next Decade.”</span> <em>Research Policy</em>, Open <span>Innovation</span>: <span>New Insights</span> and <span>Evidence</span>, 43 (5): 805–11. <a href="https://doi.org/10.1016/j.respol.2014.03.001">https://doi.org/10.1016/j.respol.2014.03.001</a>.
</div>
<div id="ref-williamson1975" class="csl-entry" role="listitem">
Williamson, Oliver E. 1975. <em>Markets and <span>Hierarchies</span>: <span>Analysis</span> and <span>Antitrust Implications</span>, <span>A Study</span> in the <span>Economics</span> of <span>Internal Organization</span></em>. <span>New York</span>: <span>The Free Press</span>.
</div>
<div id="ref-williamson1985" class="csl-entry" role="listitem">
———. 1985. <em>The <span>Economic Institutions</span> of <span>Capitalism</span>: <span>Firms</span>, <span>Markets</span>, <span>Relational Contracting</span></em>. <span>Free Press</span>.
</div>
<div id="ref-williamson2010" class="csl-entry" role="listitem">
———. 2010. <span>“Transaction <span>Cost Economics</span>: <span>The Natural Progression</span>.”</span> <em>The American Economic Review</em> 100 (3): 673–90. <a href="https://www.jstor.org/stable/27871227">https://www.jstor.org/stable/27871227</a>.
</div>
<div id="ref-windrum2004" class="csl-entry" role="listitem">
Windrum, Paul. 2004. <span>“Leveraging Technological Externalities in Complex Technologies: <span>Microsoft</span>’s Exploitation of Standards in the Browser Wars.”</span> <em>Research Policy</em> 33 (3): 385–94. <a href="https://doi.org/10.1016/j.respol.2003.09.002">https://doi.org/10.1016/j.respol.2003.09.002</a>.
</div>
<div id="ref-zajac1993" class="csl-entry" role="listitem">
Zajac, Edward J., and Cyrus P. Olsen. 1993. <span>“From <span>Transaction Cost</span> to <span>Transactional Value Analysis</span>: <span>Implications</span> for the <span>Study</span> of <span>Interorganizational Strategies</span>*.”</span> <em>Journal of Management Studies</em> 30 (1): 131–45. <a href="https://doi.org/10.1111/j.1467-6486.1993.tb00298.x">https://doi.org/10.1111/j.1467-6486.1993.tb00298.x</a>.
</div>
<div id="ref-zhang2022" class="csl-entry" role="listitem">
Zhang, Yuxia, Hao He, and Minghui Zhou. 2022. <span>“Commercial <span>Participation</span> in <span>OpenStack</span>: <span>Two Sides</span> of a <span>Coin</span>.”</span> <em>Computer</em> 55 (2): 78–84. <a href="https://doi.org/10.1109/MC.2021.3133052">https://doi.org/10.1109/MC.2021.3133052</a>.
</div>
<div id="ref-zhang2018" class="csl-entry" role="listitem">
Zhang, Yuxia, Xin Tan, Minghui Zhou, and Zhi Jin. 2018. <span>“Companies’ Domination in <span>FLOSS</span> Development: An Empirical Study of <span>OpenStack</span>.”</span> In <em>Proceedings of the 40th <span>International Conference</span> on <span>Software Engineering</span>: <span>Companion Proceeedings</span></em>, 440–41. <span>Gothenburg Sweden</span>: <span>ACM</span>. <a href="https://doi.org/10.1145/3183440.3195047">https://doi.org/10.1145/3183440.3195047</a>.
</div>
<div id="ref-zhang2021" class="csl-entry" role="listitem">
Zhang, Yuxia, Minghui Zhou, Audris Mockus, and Zhi Jin. 2021. <span>“Companies’ <span>Participation</span> in <span>OSS Development</span> of <span>OpenStack</span>.”</span> <em>IEEE Transactions on Software Engineering</em> 47 (10): 2242–59. <a href="https://doi.org/10.1109/TSE.2019.2946156">https://doi.org/10.1109/TSE.2019.2946156</a>.
</div>
<div id="ref-zhang2020a" class="csl-entry" role="listitem">
Zhang, Yuxia, Minghui Zhou, Klaas-Jan Stol, Jianyu Wu, and Zhi Jin. 2020. <span>“How <span>Do Companies Collaborate</span> in <span>Open Source Ecosystems</span>? <span>An Empirical Study</span> of <span>OpenStack</span>.”</span> In <em>2020 <span>IEEE</span>/<span>ACM</span> 42nd <span>International Conference</span> on <span>Software Engineering</span> (<span>ICSE</span>)</em>, 1196–1208. <a href="https://doi.org/10.1145/3377811.3380376">https://doi.org/10.1145/3377811.3380376</a>.
</div>
<div id="ref-zhou2017" class="csl-entry" role="listitem">
Zhou, Minghui, Qingying Chen, Audris Mockus, and Fengguang Wu. 2017. <span>“On the Scalability of <span>Linux</span> Kernel Maintainers’ Work.”</span> In <em>Proceedings of the 2017 11th <span>Joint Meeting</span> on <span>Foundations</span> of <span>Software Engineering</span></em>, 27–37. <span>Paderborn Germany</span>: <span>ACM</span>. <a href="https://doi.org/10.1145/3106237.3106287">https://doi.org/10.1145/3106237.3106287</a>.
</div>
<div id="ref-zhou2012" class="csl-entry" role="listitem">
Zhou, Minghui, and Audris Mockus. 2012. <span>“What Make Long Term Contributors: <span>Willingness</span> and Opportunity in <span>OSS</span> Community.”</span> In <em>2012 34th <span>International Conference</span> on <span>Software Engineering</span> (<span>ICSE</span>)</em>, 518–28. <a href="https://doi.org/10.1109/ICSE.2012.6227164">https://doi.org/10.1109/ICSE.2012.6227164</a>.
</div>
<div id="ref-zhou2022" class="csl-entry" role="listitem">
Zhou, Zach Zhizhong, and Vidyanand Choudhary. 2022. <span>“Impact of <span>Competition</span> from <span>Open Source Software</span> on <span>Proprietary Software</span>.”</span> <em>Production and Operations Management</em> 31 (2): 731–42. <a href="https://doi.org/10.1111/poms.13575">https://doi.org/10.1111/poms.13575</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/rmporsch\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"selector":".lightbox","loop":false,"descPosition":"bottom","openEffect":"zoom","closeEffect":"zoom"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>